#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Event_Type:
  FleetCodeError = 0
  FleetCodeExecError = 1
  PlanetCodeError = 2
  PlanetCodeExecError = 3
  Upgraded = 4
  ShipMade = 5
  PlanetHarvested = 6
  FleetWin = 7
  FleetDraw = 8
  FleetsGather = 9
  PlanetColonized = 10
  FleetLose = 11
  FleetDrop = 12
  PlanetLose = 13
  PlanetWin = 14
  CannonMade = 15
  Count = 16

  _VALUES_TO_NAMES = {
    0: "FleetCodeError",
    1: "FleetCodeExecError",
    2: "PlanetCodeError",
    3: "PlanetCodeExecError",
    4: "Upgraded",
    5: "ShipMade",
    6: "PlanetHarvested",
    7: "FleetWin",
    8: "FleetDraw",
    9: "FleetsGather",
    10: "PlanetColonized",
    11: "FleetLose",
    12: "FleetDrop",
    13: "PlanetLose",
    14: "PlanetWin",
    15: "CannonMade",
    16: "Count",
  }

  _NAMES_TO_VALUES = {
    "FleetCodeError": 0,
    "FleetCodeExecError": 1,
    "PlanetCodeError": 2,
    "PlanetCodeExecError": 3,
    "Upgraded": 4,
    "ShipMade": 5,
    "PlanetHarvested": 6,
    "FleetWin": 7,
    "FleetDraw": 8,
    "FleetsGather": 9,
    "PlanetColonized": 10,
    "FleetLose": 11,
    "FleetDrop": 12,
    "PlanetLose": 13,
    "PlanetWin": 14,
    "CannonMade": 15,
    "Count": 16,
  }

class Ressource:
  Metal = 0
  Carbon = 1
  Loicium = 2
  Count = 3

  _VALUES_TO_NAMES = {
    0: "Metal",
    1: "Carbon",
    2: "Loicium",
    3: "Count",
  }

  _NAMES_TO_VALUES = {
    "Metal": 0,
    "Carbon": 1,
    "Loicium": 2,
    "Count": 3,
  }

class PlanetTask_Enum:
  UpgradeBuilding = 0
  MakeShip = 1
  MakeCannon = 2
  Count = 3

  _VALUES_TO_NAMES = {
    0: "UpgradeBuilding",
    1: "MakeShip",
    2: "MakeCannon",
    3: "Count",
  }

  _NAMES_TO_VALUES = {
    "UpgradeBuilding": 0,
    "MakeShip": 1,
    "MakeCannon": 2,
    "Count": 3,
  }

class Building_Enum:
  CommandCenter = 0
  MetalMine = 1
  CarbonMine = 2
  LoiciumFilter = 3
  Factory = 4
  Laboratory = 5
  CarbonicCentral = 6
  SolarCentral = 7
  GeothermicCentral = 8
  Count = 9

  _VALUES_TO_NAMES = {
    0: "CommandCenter",
    1: "MetalMine",
    2: "CarbonMine",
    3: "LoiciumFilter",
    4: "Factory",
    5: "Laboratory",
    6: "CarbonicCentral",
    7: "SolarCentral",
    8: "GeothermicCentral",
    9: "Count",
  }

  _NAMES_TO_VALUES = {
    "CommandCenter": 0,
    "MetalMine": 1,
    "CarbonMine": 2,
    "LoiciumFilter": 3,
    "Factory": 4,
    "Laboratory": 5,
    "CarbonicCentral": 6,
    "SolarCentral": 7,
    "GeothermicCentral": 8,
    "Count": 9,
  }

class Ship_Enum:
  Mosquito = 0
  Hornet = 1
  Vulture = 2
  Dragon = 3
  Behemoth = 4
  Azathoth = 5
  Queen = 6
  Cargo = 7
  LargeCargo = 8
  Count = 9

  _VALUES_TO_NAMES = {
    0: "Mosquito",
    1: "Hornet",
    2: "Vulture",
    3: "Dragon",
    4: "Behemoth",
    5: "Azathoth",
    6: "Queen",
    7: "Cargo",
    8: "LargeCargo",
    9: "Count",
  }

  _NAMES_TO_VALUES = {
    "Mosquito": 0,
    "Hornet": 1,
    "Vulture": 2,
    "Dragon": 3,
    "Behemoth": 4,
    "Azathoth": 5,
    "Queen": 6,
    "Cargo": 7,
    "LargeCargo": 8,
    "Count": 9,
  }

class Cannon_Enum:
  Cannon1 = 0
  Cannon2 = 1
  Cannon3 = 2
  Cannon4 = 3
  Cannon5 = 4
  Cannon6 = 5
  Count = 6

  _VALUES_TO_NAMES = {
    0: "Cannon1",
    1: "Cannon2",
    2: "Cannon3",
    3: "Cannon4",
    4: "Cannon5",
    5: "Cannon6",
    6: "Count",
  }

  _NAMES_TO_VALUES = {
    "Cannon1": 0,
    "Cannon2": 1,
    "Cannon3": 2,
    "Cannon4": 3,
    "Cannon5": 4,
    "Cannon6": 5,
    "Count": 6,
  }

class FleetTask_Enum:
  Move = 0
  Harvest = 1
  Colonize = 2
  Count = 3

  _VALUES_TO_NAMES = {
    0: "Move",
    1: "Harvest",
    2: "Colonize",
    3: "Count",
  }

  _NAMES_TO_VALUES = {
    "Move": 0,
    "Harvest": 1,
    "Colonize": 2,
    "Count": 3,
  }

class FleetAction_Type:
  Nothing = 0
  Move = 1
  Harvest = 2
  Colonize = 3

  _VALUES_TO_NAMES = {
    0: "Nothing",
    1: "Move",
    2: "Harvest",
    3: "Colonize",
  }

  _NAMES_TO_VALUES = {
    "Nothing": 0,
    "Move": 1,
    "Harvest": 2,
    "Colonize": 3,
  }

class Sort_Type:
  Name = 0
  X = 1
  Y = 2
  Z = 3
  M = 4
  C = 5
  L = 6

  _VALUES_TO_NAMES = {
    0: "Name",
    1: "X",
    2: "Y",
    3: "Z",
    4: "M",
    5: "C",
    6: "L",
  }

  _NAMES_TO_VALUES = {
    "Name": 0,
    "X": 1,
    "Y": 2,
    "Z": 3,
    "M": 4,
    "C": 5,
    "L": 6,
  }


class Coord:
  """
  Attributes:
   - X
   - Y
   - Z
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'X', None, None, ), # 1
    (2, TType.I32, 'Y', None, None, ), # 2
    (3, TType.I32, 'Z', None, None, ), # 3
  )

  def __init__(self, X=None, Y=None, Z=None,):
    self.X = X
    self.Y = Y
    self.Z = Z

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.X = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.Y = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.Z = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Coord')
    if self.X is not None:
      oprot.writeFieldBegin('X', TType.I32, 1)
      oprot.writeI32(self.X)
      oprot.writeFieldEnd()
    if self.Y is not None:
      oprot.writeFieldBegin('Y', TType.I32, 2)
      oprot.writeI32(self.Y)
      oprot.writeFieldEnd()
    if self.Z is not None:
      oprot.writeFieldBegin('Z', TType.I32, 3)
      oprot.writeI32(self.Z)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Event:
  """
  Attributes:
   - id
   - time
   - type
   - comment
   - value
   - viewed
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'id', None, None, ), # 1
    (2, TType.I32, 'time', None, None, ), # 2
    (3, TType.I32, 'type', None, None, ), # 3
    (4, TType.STRING, 'comment', None, None, ), # 4
    (5, TType.I32, 'value', None, None, ), # 5
    (6, TType.BOOL, 'viewed', None, None, ), # 6
  )

  def __init__(self, id=None, time=None, type=None, comment=None, value=None, viewed=None,):
    self.id = id
    self.time = time
    self.type = type
    self.comment = comment
    self.value = value
    self.viewed = viewed

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.time = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.comment = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.value = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.BOOL:
          self.viewed = iprot.readBool();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Event')
    if self.id is not None:
      oprot.writeFieldBegin('id', TType.I32, 1)
      oprot.writeI32(self.id)
      oprot.writeFieldEnd()
    if self.time is not None:
      oprot.writeFieldBegin('time', TType.I32, 2)
      oprot.writeI32(self.time)
      oprot.writeFieldEnd()
    if self.type is not None:
      oprot.writeFieldBegin('type', TType.I32, 3)
      oprot.writeI32(self.type)
      oprot.writeFieldEnd()
    if self.comment is not None:
      oprot.writeFieldBegin('comment', TType.STRING, 4)
      oprot.writeString(self.comment)
      oprot.writeFieldEnd()
    if self.value is not None:
      oprot.writeFieldBegin('value', TType.I32, 5)
      oprot.writeI32(self.value)
      oprot.writeFieldEnd()
    if self.viewed is not None:
      oprot.writeFieldBegin('viewed', TType.BOOL, 6)
      oprot.writeBool(self.viewed)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class CodeData:
  """
  Attributes:
   - blocklyCode
   - code
   - lastError
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'blocklyCode', None, None, ), # 1
    (2, TType.STRING, 'code', None, None, ), # 2
    None, # 3
    (4, TType.STRING, 'lastError', None, None, ), # 4
  )

  def __init__(self, blocklyCode=None, code=None, lastError=None,):
    self.blocklyCode = blocklyCode
    self.code = code
    self.lastError = lastError

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.blocklyCode = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.code = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRING:
          self.lastError = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('CodeData')
    if self.blocklyCode is not None:
      oprot.writeFieldBegin('blocklyCode', TType.STRING, 1)
      oprot.writeString(self.blocklyCode)
      oprot.writeFieldEnd()
    if self.code is not None:
      oprot.writeFieldBegin('code', TType.STRING, 2)
      oprot.writeString(self.code)
      oprot.writeFieldEnd()
    if self.lastError is not None:
      oprot.writeFieldBegin('lastError', TType.STRING, 4)
      oprot.writeString(self.lastError)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Player:
  """
  Attributes:
   - id
   - login
   - password
   - fleetsCode
   - planetsCode
   - tutoDisplayed
   - mainPlanet
   - score
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'id', None, None, ), # 1
    (2, TType.STRING, 'login', None, None, ), # 2
    (3, TType.STRING, 'password', None, None, ), # 3
    (4, TType.STRUCT, 'fleetsCode', (CodeData, CodeData.thrift_spec), None, ), # 4
    (5, TType.STRUCT, 'planetsCode', (CodeData, CodeData.thrift_spec), None, ), # 5
    None, # 6
    (7, TType.MAP, 'tutoDisplayed', (TType.STRING,None,TType.I32,None), None, ), # 7
    (8, TType.STRUCT, 'mainPlanet', (Coord, Coord.thrift_spec), None, ), # 8
    (9, TType.I64, 'score', None, 0, ), # 9
  )

  def __init__(self, id=None, login=None, password=None, fleetsCode=None, planetsCode=None, tutoDisplayed=None, mainPlanet=None, score=thrift_spec[9][4],):
    self.id = id
    self.login = login
    self.password = password
    self.fleetsCode = fleetsCode
    self.planetsCode = planetsCode
    self.tutoDisplayed = tutoDisplayed
    self.mainPlanet = mainPlanet
    self.score = score

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.id = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.login = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.STRING:
          self.password = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.fleetsCode = CodeData()
          self.fleetsCode.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.STRUCT:
          self.planetsCode = CodeData()
          self.planetsCode.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.MAP:
          self.tutoDisplayed = {}
          (_ktype1, _vtype2, _size0 ) = iprot.readMapBegin() 
          for _i4 in xrange(_size0):
            _key5 = iprot.readString();
            _val6 = iprot.readI32();
            self.tutoDisplayed[_key5] = _val6
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.STRUCT:
          self.mainPlanet = Coord()
          self.mainPlanet.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 9:
        if ftype == TType.I64:
          self.score = iprot.readI64();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Player')
    if self.id is not None:
      oprot.writeFieldBegin('id', TType.I32, 1)
      oprot.writeI32(self.id)
      oprot.writeFieldEnd()
    if self.login is not None:
      oprot.writeFieldBegin('login', TType.STRING, 2)
      oprot.writeString(self.login)
      oprot.writeFieldEnd()
    if self.password is not None:
      oprot.writeFieldBegin('password', TType.STRING, 3)
      oprot.writeString(self.password)
      oprot.writeFieldEnd()
    if self.fleetsCode is not None:
      oprot.writeFieldBegin('fleetsCode', TType.STRUCT, 4)
      self.fleetsCode.write(oprot)
      oprot.writeFieldEnd()
    if self.planetsCode is not None:
      oprot.writeFieldBegin('planetsCode', TType.STRUCT, 5)
      self.planetsCode.write(oprot)
      oprot.writeFieldEnd()
    if self.tutoDisplayed is not None:
      oprot.writeFieldBegin('tutoDisplayed', TType.MAP, 7)
      oprot.writeMapBegin(TType.STRING, TType.I32, len(self.tutoDisplayed))
      for kiter7,viter8 in self.tutoDisplayed.items():
        oprot.writeString(kiter7)
        oprot.writeI32(viter8)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.mainPlanet is not None:
      oprot.writeFieldBegin('mainPlanet', TType.STRUCT, 8)
      self.mainPlanet.write(oprot)
      oprot.writeFieldEnd()
    if self.score is not None:
      oprot.writeFieldBegin('score', TType.I64, 9)
      oprot.writeI64(self.score)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class RessourceSet:
  """
  Attributes:
   - tab
  """

  thrift_spec = (
    None, # 0
    (1, TType.LIST, 'tab', (TType.I32,None), None, ), # 1
  )

  def __init__(self, tab=None,):
    self.tab = tab

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.LIST:
          self.tab = []
          (_etype12, _size9) = iprot.readListBegin()
          for _i13 in xrange(_size9):
            _elem14 = iprot.readI32();
            self.tab.append(_elem14)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('RessourceSet')
    if self.tab is not None:
      oprot.writeFieldBegin('tab', TType.LIST, 1)
      oprot.writeListBegin(TType.I32, len(self.tab))
      for iter15 in self.tab:
        oprot.writeI32(iter15)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PlanetTask:
  """
  Attributes:
   - type
   - value
   - value2
   - lauchTime
   - duration
   - startCos
   - expired
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'type', None,     0, ), # 1
    (2, TType.I32, 'value', None, None, ), # 2
    (3, TType.I32, 'value2', None, None, ), # 3
    (4, TType.I32, 'lauchTime', None, None, ), # 4
    (5, TType.I32, 'duration', None, None, ), # 5
    (6, TType.STRUCT, 'startCos', (RessourceSet, RessourceSet.thrift_spec), None, ), # 6
    (7, TType.BOOL, 'expired', None, None, ), # 7
  )

  def __init__(self, type=thrift_spec[1][4], value=None, value2=None, lauchTime=None, duration=None, startCos=None, expired=None,):
    self.type = type
    self.value = value
    self.value2 = value2
    self.lauchTime = lauchTime
    self.duration = duration
    self.startCos = startCos
    self.expired = expired

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.value = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.value2 = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I32:
          self.lauchTime = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.duration = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRUCT:
          self.startCos = RessourceSet()
          self.startCos.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.BOOL:
          self.expired = iprot.readBool();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PlanetTask')
    if self.type is not None:
      oprot.writeFieldBegin('type', TType.I32, 1)
      oprot.writeI32(self.type)
      oprot.writeFieldEnd()
    if self.value is not None:
      oprot.writeFieldBegin('value', TType.I32, 2)
      oprot.writeI32(self.value)
      oprot.writeFieldEnd()
    if self.value2 is not None:
      oprot.writeFieldBegin('value2', TType.I32, 3)
      oprot.writeI32(self.value2)
      oprot.writeFieldEnd()
    if self.lauchTime is not None:
      oprot.writeFieldBegin('lauchTime', TType.I32, 4)
      oprot.writeI32(self.lauchTime)
      oprot.writeFieldEnd()
    if self.duration is not None:
      oprot.writeFieldBegin('duration', TType.I32, 5)
      oprot.writeI32(self.duration)
      oprot.writeFieldEnd()
    if self.startCos is not None:
      oprot.writeFieldBegin('startCos', TType.STRUCT, 6)
      self.startCos.write(oprot)
      oprot.writeFieldEnd()
    if self.expired is not None:
      oprot.writeFieldBegin('expired', TType.BOOL, 7)
      oprot.writeBool(self.expired)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Building:
  """
  Attributes:
   - index
   - price
   - coef
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.I32, 'index', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.STRUCT, 'price', (RessourceSet, RessourceSet.thrift_spec), None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.DOUBLE, 'coef', None, None, ), # 30
  )

  def __init__(self, index=None, price=None, coef=None,):
    self.index = index
    self.price = price
    self.coef = coef

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.I32:
          self.index = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRUCT:
          self.price = RessourceSet()
          self.price.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.DOUBLE:
          self.coef = iprot.readDouble();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Building')
    if self.index is not None:
      oprot.writeFieldBegin('index', TType.I32, 10)
      oprot.writeI32(self.index)
      oprot.writeFieldEnd()
    if self.price is not None:
      oprot.writeFieldBegin('price', TType.STRUCT, 20)
      self.price.write(oprot)
      oprot.writeFieldEnd()
    if self.coef is not None:
      oprot.writeFieldBegin('coef', TType.DOUBLE, 30)
      oprot.writeDouble(self.coef)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Ship:
  """
  Attributes:
   - index
   - price
   - life
   - power
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.I32, 'index', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.STRUCT, 'price', (RessourceSet, RessourceSet.thrift_spec), None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.I32, 'life', None, None, ), # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    (40, TType.I32, 'power', None, None, ), # 40
  )

  def __init__(self, index=None, price=None, life=None, power=None,):
    self.index = index
    self.price = price
    self.life = life
    self.power = power

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.I32:
          self.index = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRUCT:
          self.price = RessourceSet()
          self.price.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.I32:
          self.life = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 40:
        if ftype == TType.I32:
          self.power = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Ship')
    if self.index is not None:
      oprot.writeFieldBegin('index', TType.I32, 10)
      oprot.writeI32(self.index)
      oprot.writeFieldEnd()
    if self.price is not None:
      oprot.writeFieldBegin('price', TType.STRUCT, 20)
      self.price.write(oprot)
      oprot.writeFieldEnd()
    if self.life is not None:
      oprot.writeFieldBegin('life', TType.I32, 30)
      oprot.writeI32(self.life)
      oprot.writeFieldEnd()
    if self.power is not None:
      oprot.writeFieldBegin('power', TType.I32, 40)
      oprot.writeI32(self.power)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Cannon:
  """
  Attributes:
   - index
   - price
   - life
   - power
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.I32, 'index', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.STRUCT, 'price', (RessourceSet, RessourceSet.thrift_spec), None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.I32, 'life', None, None, ), # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    (40, TType.I32, 'power', None, None, ), # 40
  )

  def __init__(self, index=None, price=None, life=None, power=None,):
    self.index = index
    self.price = price
    self.life = life
    self.power = power

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.I32:
          self.index = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRUCT:
          self.price = RessourceSet()
          self.price.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.I32:
          self.life = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 40:
        if ftype == TType.I32:
          self.power = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Cannon')
    if self.index is not None:
      oprot.writeFieldBegin('index', TType.I32, 10)
      oprot.writeI32(self.index)
      oprot.writeFieldEnd()
    if self.price is not None:
      oprot.writeFieldBegin('price', TType.STRUCT, 20)
      self.price.write(oprot)
      oprot.writeFieldEnd()
    if self.life is not None:
      oprot.writeFieldBegin('life', TType.I32, 30)
      oprot.writeI32(self.life)
      oprot.writeFieldEnd()
    if self.power is not None:
      oprot.writeFieldBegin('power', TType.I32, 40)
      oprot.writeI32(self.power)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class FleetTask:
  """
  Attributes:
   - type
   - lauchTime
   - duration
   - position
   - expired
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'type', None, None, ), # 1
    (2, TType.I32, 'lauchTime', None, None, ), # 2
    (3, TType.I32, 'duration', None, None, ), # 3
    (4, TType.STRUCT, 'position', (Coord, Coord.thrift_spec), None, ), # 4
    (5, TType.BOOL, 'expired', None, None, ), # 5
  )

  def __init__(self, type=None, lauchTime=None, duration=None, position=None, expired=None,):
    self.type = type
    self.lauchTime = lauchTime
    self.duration = duration
    self.position = position
    self.expired = expired

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.type = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.I32:
          self.lauchTime = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.duration = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.STRUCT:
          self.position = Coord()
          self.position.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.BOOL:
          self.expired = iprot.readBool();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('FleetTask')
    if self.type is not None:
      oprot.writeFieldBegin('type', TType.I32, 1)
      oprot.writeI32(self.type)
      oprot.writeFieldEnd()
    if self.lauchTime is not None:
      oprot.writeFieldBegin('lauchTime', TType.I32, 2)
      oprot.writeI32(self.lauchTime)
      oprot.writeFieldEnd()
    if self.duration is not None:
      oprot.writeFieldBegin('duration', TType.I32, 3)
      oprot.writeI32(self.duration)
      oprot.writeFieldEnd()
    if self.position is not None:
      oprot.writeFieldBegin('position', TType.STRUCT, 4)
      self.position.write(oprot)
      oprot.writeFieldEnd()
    if self.expired is not None:
      oprot.writeFieldBegin('expired', TType.BOOL, 5)
      oprot.writeBool(self.expired)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Planet:
  """
  Attributes:
   - name
   - coord
   - playerId
   - buildingList
   - taskQueue
   - ressourceSet
   - eventList
   - cannonTab
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'name', None, None, ), # 1
    (2, TType.STRUCT, 'coord', (Coord, Coord.thrift_spec), None, ), # 2
    (3, TType.I32, 'playerId', None, None, ), # 3
    (4, TType.LIST, 'buildingList', (TType.I32,None), None, ), # 4
    (5, TType.LIST, 'taskQueue', (TType.STRUCT,(PlanetTask, PlanetTask.thrift_spec)), None, ), # 5
    (6, TType.STRUCT, 'ressourceSet', (RessourceSet, RessourceSet.thrift_spec), None, ), # 6
    (7, TType.LIST, 'eventList', (TType.STRUCT,(Event, Event.thrift_spec)), None, ), # 7
    (8, TType.LIST, 'cannonTab', (TType.I32,None), None, ), # 8
  )

  def __init__(self, name=None, coord=None, playerId=None, buildingList=None, taskQueue=None, ressourceSet=None, eventList=None, cannonTab=None,):
    self.name = name
    self.coord = coord
    self.playerId = playerId
    self.buildingList = buildingList
    self.taskQueue = taskQueue
    self.ressourceSet = ressourceSet
    self.eventList = eventList
    self.cannonTab = cannonTab

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.coord = Coord()
          self.coord.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.I32:
          self.playerId = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.LIST:
          self.buildingList = []
          (_etype19, _size16) = iprot.readListBegin()
          for _i20 in xrange(_size16):
            _elem21 = iprot.readI32();
            self.buildingList.append(_elem21)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.LIST:
          self.taskQueue = []
          (_etype25, _size22) = iprot.readListBegin()
          for _i26 in xrange(_size22):
            _elem27 = PlanetTask()
            _elem27.read(iprot)
            self.taskQueue.append(_elem27)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.STRUCT:
          self.ressourceSet = RessourceSet()
          self.ressourceSet.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.LIST:
          self.eventList = []
          (_etype31, _size28) = iprot.readListBegin()
          for _i32 in xrange(_size28):
            _elem33 = Event()
            _elem33.read(iprot)
            self.eventList.append(_elem33)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 8:
        if ftype == TType.LIST:
          self.cannonTab = []
          (_etype37, _size34) = iprot.readListBegin()
          for _i38 in xrange(_size34):
            _elem39 = iprot.readI32();
            self.cannonTab.append(_elem39)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Planet')
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 1)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.coord is not None:
      oprot.writeFieldBegin('coord', TType.STRUCT, 2)
      self.coord.write(oprot)
      oprot.writeFieldEnd()
    if self.playerId is not None:
      oprot.writeFieldBegin('playerId', TType.I32, 3)
      oprot.writeI32(self.playerId)
      oprot.writeFieldEnd()
    if self.buildingList is not None:
      oprot.writeFieldBegin('buildingList', TType.LIST, 4)
      oprot.writeListBegin(TType.I32, len(self.buildingList))
      for iter40 in self.buildingList:
        oprot.writeI32(iter40)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.taskQueue is not None:
      oprot.writeFieldBegin('taskQueue', TType.LIST, 5)
      oprot.writeListBegin(TType.STRUCT, len(self.taskQueue))
      for iter41 in self.taskQueue:
        iter41.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.ressourceSet is not None:
      oprot.writeFieldBegin('ressourceSet', TType.STRUCT, 6)
      self.ressourceSet.write(oprot)
      oprot.writeFieldEnd()
    if self.eventList is not None:
      oprot.writeFieldBegin('eventList', TType.LIST, 7)
      oprot.writeListBegin(TType.STRUCT, len(self.eventList))
      for iter42 in self.eventList:
        iter42.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.cannonTab is not None:
      oprot.writeFieldBegin('cannonTab', TType.LIST, 8)
      oprot.writeListBegin(TType.I32, len(self.cannonTab))
      for iter43 in self.cannonTab:
        oprot.writeI32(iter43)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Fleet:
  """
  Attributes:
   - id
   - playerId
   - coord
   - origin
   - name
   - shipList
   - ressourceSet
   - taskQueue
   - eventList
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.I64, 'id', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.I32, 'playerId', None, None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.STRUCT, 'coord', (Coord, Coord.thrift_spec), None, ), # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    (40, TType.STRUCT, 'origin', (Coord, Coord.thrift_spec), None, ), # 40
    None, # 41
    None, # 42
    None, # 43
    None, # 44
    None, # 45
    None, # 46
    None, # 47
    None, # 48
    None, # 49
    (50, TType.STRING, 'name', None, None, ), # 50
    None, # 51
    None, # 52
    None, # 53
    None, # 54
    None, # 55
    None, # 56
    None, # 57
    None, # 58
    None, # 59
    (60, TType.LIST, 'shipList', (TType.I32,None), None, ), # 60
    None, # 61
    None, # 62
    None, # 63
    None, # 64
    None, # 65
    None, # 66
    None, # 67
    None, # 68
    None, # 69
    (70, TType.STRUCT, 'ressourceSet', (RessourceSet, RessourceSet.thrift_spec), None, ), # 70
    None, # 71
    None, # 72
    None, # 73
    None, # 74
    None, # 75
    None, # 76
    None, # 77
    None, # 78
    None, # 79
    (80, TType.LIST, 'taskQueue', (TType.STRUCT,(FleetTask, FleetTask.thrift_spec)), None, ), # 80
    None, # 81
    None, # 82
    None, # 83
    None, # 84
    None, # 85
    None, # 86
    None, # 87
    None, # 88
    None, # 89
    (90, TType.LIST, 'eventList', (TType.STRUCT,(Event, Event.thrift_spec)), None, ), # 90
  )

  def __init__(self, id=None, playerId=None, coord=None, origin=None, name=None, shipList=None, ressourceSet=None, taskQueue=None, eventList=None,):
    self.id = id
    self.playerId = playerId
    self.coord = coord
    self.origin = origin
    self.name = name
    self.shipList = shipList
    self.ressourceSet = ressourceSet
    self.taskQueue = taskQueue
    self.eventList = eventList

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.I64:
          self.id = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.I32:
          self.playerId = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.STRUCT:
          self.coord = Coord()
          self.coord.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 40:
        if ftype == TType.STRUCT:
          self.origin = Coord()
          self.origin.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 50:
        if ftype == TType.STRING:
          self.name = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 60:
        if ftype == TType.LIST:
          self.shipList = []
          (_etype47, _size44) = iprot.readListBegin()
          for _i48 in xrange(_size44):
            _elem49 = iprot.readI32();
            self.shipList.append(_elem49)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 70:
        if ftype == TType.STRUCT:
          self.ressourceSet = RessourceSet()
          self.ressourceSet.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 80:
        if ftype == TType.LIST:
          self.taskQueue = []
          (_etype53, _size50) = iprot.readListBegin()
          for _i54 in xrange(_size50):
            _elem55 = FleetTask()
            _elem55.read(iprot)
            self.taskQueue.append(_elem55)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 90:
        if ftype == TType.LIST:
          self.eventList = []
          (_etype59, _size56) = iprot.readListBegin()
          for _i60 in xrange(_size56):
            _elem61 = Event()
            _elem61.read(iprot)
            self.eventList.append(_elem61)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Fleet')
    if self.id is not None:
      oprot.writeFieldBegin('id', TType.I64, 10)
      oprot.writeI64(self.id)
      oprot.writeFieldEnd()
    if self.playerId is not None:
      oprot.writeFieldBegin('playerId', TType.I32, 20)
      oprot.writeI32(self.playerId)
      oprot.writeFieldEnd()
    if self.coord is not None:
      oprot.writeFieldBegin('coord', TType.STRUCT, 30)
      self.coord.write(oprot)
      oprot.writeFieldEnd()
    if self.origin is not None:
      oprot.writeFieldBegin('origin', TType.STRUCT, 40)
      self.origin.write(oprot)
      oprot.writeFieldEnd()
    if self.name is not None:
      oprot.writeFieldBegin('name', TType.STRING, 50)
      oprot.writeString(self.name)
      oprot.writeFieldEnd()
    if self.shipList is not None:
      oprot.writeFieldBegin('shipList', TType.LIST, 60)
      oprot.writeListBegin(TType.I32, len(self.shipList))
      for iter62 in self.shipList:
        oprot.writeI32(iter62)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.ressourceSet is not None:
      oprot.writeFieldBegin('ressourceSet', TType.STRUCT, 70)
      self.ressourceSet.write(oprot)
      oprot.writeFieldEnd()
    if self.taskQueue is not None:
      oprot.writeFieldBegin('taskQueue', TType.LIST, 80)
      oprot.writeListBegin(TType.STRUCT, len(self.taskQueue))
      for iter63 in self.taskQueue:
        iter63.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.eventList is not None:
      oprot.writeFieldBegin('eventList', TType.LIST, 90)
      oprot.writeListBegin(TType.STRUCT, len(self.eventList))
      for iter64 in self.eventList:
        iter64.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class FleetAction:
  """
  Attributes:
   - action
   - target
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'action', None, None, ), # 1
    (2, TType.STRUCT, 'target', (Coord, Coord.thrift_spec), None, ), # 2
  )

  def __init__(self, action=None, target=None,):
    self.action = action
    self.target = target

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.action = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRUCT:
          self.target = Coord()
          self.target.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('FleetAction')
    if self.action is not None:
      oprot.writeFieldBegin('action', TType.I32, 1)
      oprot.writeI32(self.action)
      oprot.writeFieldEnd()
    if self.target is not None:
      oprot.writeFieldBegin('target', TType.STRUCT, 2)
      self.target.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class FleetFightInfo:
  """
  Attributes:
   - before
   - after
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.STRUCT, 'before', (Fleet, Fleet.thrift_spec), None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.STRUCT, 'after', (Fleet, Fleet.thrift_spec), None, ), # 20
  )

  def __init__(self, before=None, after=None,):
    self.before = before
    self.after = after

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.STRUCT:
          self.before = Fleet()
          self.before.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRUCT:
          self.after = Fleet()
          self.after.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('FleetFightInfo')
    if self.before is not None:
      oprot.writeFieldBegin('before', TType.STRUCT, 10)
      self.before.write(oprot)
      oprot.writeFieldEnd()
    if self.after is not None:
      oprot.writeFieldBegin('after', TType.STRUCT, 20)
      self.after.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class FleetReport:
  """
  Attributes:
   - isDead
   - hasFight
   - enemySet
   - fightInfo
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.BOOL, 'isDead', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.BOOL, 'hasFight', None, None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.SET, 'enemySet', (TType.I32,None), None, ), # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    (40, TType.STRUCT, 'fightInfo', (FleetFightInfo, FleetFightInfo.thrift_spec), None, ), # 40
  )

  def __init__(self, isDead=None, hasFight=None, enemySet=None, fightInfo=None,):
    self.isDead = isDead
    self.hasFight = hasFight
    self.enemySet = enemySet
    self.fightInfo = fightInfo

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.BOOL:
          self.isDead = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.BOOL:
          self.hasFight = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.SET:
          self.enemySet = set()
          (_etype68, _size65) = iprot.readSetBegin()
          for _i69 in xrange(_size65):
            _elem70 = iprot.readI32();
            self.enemySet.add(_elem70)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      elif fid == 40:
        if ftype == TType.STRUCT:
          self.fightInfo = FleetFightInfo()
          self.fightInfo.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('FleetReport')
    if self.isDead is not None:
      oprot.writeFieldBegin('isDead', TType.BOOL, 10)
      oprot.writeBool(self.isDead)
      oprot.writeFieldEnd()
    if self.hasFight is not None:
      oprot.writeFieldBegin('hasFight', TType.BOOL, 20)
      oprot.writeBool(self.hasFight)
      oprot.writeFieldEnd()
    if self.enemySet is not None:
      oprot.writeFieldBegin('enemySet', TType.SET, 30)
      oprot.writeSetBegin(TType.I32, len(self.enemySet))
      for iter71 in self.enemySet:
        oprot.writeI32(iter71)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    if self.fightInfo is not None:
      oprot.writeFieldBegin('fightInfo', TType.STRUCT, 40)
      self.fightInfo.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PlanetFightInfo:
  """
  Attributes:
   - before
   - after
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.STRUCT, 'before', (Planet, Planet.thrift_spec), None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.STRUCT, 'after', (Planet, Planet.thrift_spec), None, ), # 20
  )

  def __init__(self, before=None, after=None,):
    self.before = before
    self.after = after

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.STRUCT:
          self.before = Planet()
          self.before.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.STRUCT:
          self.after = Planet()
          self.after.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PlanetFightInfo')
    if self.before is not None:
      oprot.writeFieldBegin('before', TType.STRUCT, 10)
      self.before.write(oprot)
      oprot.writeFieldEnd()
    if self.after is not None:
      oprot.writeFieldBegin('after', TType.STRUCT, 20)
      self.after.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PlanetReport:
  """
  Attributes:
   - isDead
   - hasFight
   - enemySet
   - fightInfo
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.BOOL, 'isDead', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.BOOL, 'hasFight', None, None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.SET, 'enemySet', (TType.I32,None), None, ), # 30
    None, # 31
    None, # 32
    None, # 33
    None, # 34
    None, # 35
    None, # 36
    None, # 37
    None, # 38
    None, # 39
    (40, TType.STRUCT, 'fightInfo', (PlanetFightInfo, PlanetFightInfo.thrift_spec), None, ), # 40
  )

  def __init__(self, isDead=None, hasFight=None, enemySet=None, fightInfo=None,):
    self.isDead = isDead
    self.hasFight = hasFight
    self.enemySet = enemySet
    self.fightInfo = fightInfo

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.BOOL:
          self.isDead = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.BOOL:
          self.hasFight = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.SET:
          self.enemySet = set()
          (_etype75, _size72) = iprot.readSetBegin()
          for _i76 in xrange(_size72):
            _elem77 = iprot.readI32();
            self.enemySet.add(_elem77)
          iprot.readSetEnd()
        else:
          iprot.skip(ftype)
      elif fid == 40:
        if ftype == TType.STRUCT:
          self.fightInfo = PlanetFightInfo()
          self.fightInfo.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PlanetReport')
    if self.isDead is not None:
      oprot.writeFieldBegin('isDead', TType.BOOL, 10)
      oprot.writeBool(self.isDead)
      oprot.writeFieldEnd()
    if self.hasFight is not None:
      oprot.writeFieldBegin('hasFight', TType.BOOL, 20)
      oprot.writeBool(self.hasFight)
      oprot.writeFieldEnd()
    if self.enemySet is not None:
      oprot.writeFieldBegin('enemySet', TType.SET, 30)
      oprot.writeSetBegin(TType.I32, len(self.enemySet))
      for iter78 in self.enemySet:
        oprot.writeI32(iter78)
      oprot.writeSetEnd()
      oprot.writeFieldEnd()
    if self.fightInfo is not None:
      oprot.writeFieldBegin('fightInfo', TType.STRUCT, 40)
      self.fightInfo.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class FightReport:
  """
  Attributes:
   - fleetList
   - hasPlanet
   - planet
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.LIST, 'fleetList', (TType.STRUCT,(FleetReport, FleetReport.thrift_spec)), None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.BOOL, 'hasPlanet', None, None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.STRUCT, 'planet', (PlanetReport, PlanetReport.thrift_spec), None, ), # 30
  )

  def __init__(self, fleetList=None, hasPlanet=None, planet=None,):
    self.fleetList = fleetList
    self.hasPlanet = hasPlanet
    self.planet = planet

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.LIST:
          self.fleetList = []
          (_etype82, _size79) = iprot.readListBegin()
          for _i83 in xrange(_size79):
            _elem84 = FleetReport()
            _elem84.read(iprot)
            self.fleetList.append(_elem84)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.BOOL:
          self.hasPlanet = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.STRUCT:
          self.planet = PlanetReport()
          self.planet.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('FightReport')
    if self.fleetList is not None:
      oprot.writeFieldBegin('fleetList', TType.LIST, 10)
      oprot.writeListBegin(TType.STRUCT, len(self.fleetList))
      for iter85 in self.fleetList:
        iter85.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.hasPlanet is not None:
      oprot.writeFieldBegin('hasPlanet', TType.BOOL, 20)
      oprot.writeBool(self.hasPlanet)
      oprot.writeFieldEnd()
    if self.planet is not None:
      oprot.writeFieldBegin('planet', TType.STRUCT, 30)
      self.planet.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class Universe:
  """
  Attributes:
   - playerMap
   - planetMap
   - fleetMap
   - reportMap
   - nextPlayerID
   - nextFleetID
   - time
  """

  thrift_spec = (
    None, # 0
    (1, TType.MAP, 'playerMap', (TType.I32,None,TType.STRUCT,(Player, Player.thrift_spec)), None, ), # 1
    (2, TType.MAP, 'planetMap', (TType.STRUCT,(Coord, Coord.thrift_spec),TType.STRUCT,(Planet, Planet.thrift_spec)), None, ), # 2
    (3, TType.MAP, 'fleetMap', (TType.I64,None,TType.STRUCT,(Fleet, Fleet.thrift_spec)), None, ), # 3
    (4, TType.MAP, 'reportMap', (TType.I32,None,TType.STRUCT,(FightReport, FightReport.thrift_spec)), None, ), # 4
    (5, TType.I32, 'nextPlayerID', None, None, ), # 5
    (6, TType.I64, 'nextFleetID', None, None, ), # 6
    (7, TType.I32, 'time', None, None, ), # 7
  )

  def __init__(self, playerMap=None, planetMap=None, fleetMap=None, reportMap=None, nextPlayerID=None, nextFleetID=None, time=None,):
    self.playerMap = playerMap
    self.planetMap = planetMap
    self.fleetMap = fleetMap
    self.reportMap = reportMap
    self.nextPlayerID = nextPlayerID
    self.nextFleetID = nextFleetID
    self.time = time

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.MAP:
          self.playerMap = {}
          (_ktype87, _vtype88, _size86 ) = iprot.readMapBegin() 
          for _i90 in xrange(_size86):
            _key91 = iprot.readI32();
            _val92 = Player()
            _val92.read(iprot)
            self.playerMap[_key91] = _val92
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.MAP:
          self.planetMap = {}
          (_ktype94, _vtype95, _size93 ) = iprot.readMapBegin() 
          for _i97 in xrange(_size93):
            _key98 = Coord()
            _key98.read(iprot)
            _val99 = Planet()
            _val99.read(iprot)
            self.planetMap[_key98] = _val99
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.MAP:
          self.fleetMap = {}
          (_ktype101, _vtype102, _size100 ) = iprot.readMapBegin() 
          for _i104 in xrange(_size100):
            _key105 = iprot.readI64();
            _val106 = Fleet()
            _val106.read(iprot)
            self.fleetMap[_key105] = _val106
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.MAP:
          self.reportMap = {}
          (_ktype108, _vtype109, _size107 ) = iprot.readMapBegin() 
          for _i111 in xrange(_size107):
            _key112 = iprot.readI32();
            _val113 = FightReport()
            _val113.read(iprot)
            self.reportMap[_key112] = _val113
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 5:
        if ftype == TType.I32:
          self.nextPlayerID = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 6:
        if ftype == TType.I64:
          self.nextFleetID = iprot.readI64();
        else:
          iprot.skip(ftype)
      elif fid == 7:
        if ftype == TType.I32:
          self.time = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('Universe')
    if self.playerMap is not None:
      oprot.writeFieldBegin('playerMap', TType.MAP, 1)
      oprot.writeMapBegin(TType.I32, TType.STRUCT, len(self.playerMap))
      for kiter114,viter115 in self.playerMap.items():
        oprot.writeI32(kiter114)
        viter115.write(oprot)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.planetMap is not None:
      oprot.writeFieldBegin('planetMap', TType.MAP, 2)
      oprot.writeMapBegin(TType.STRUCT, TType.STRUCT, len(self.planetMap))
      for kiter116,viter117 in self.planetMap.items():
        kiter116.write(oprot)
        viter117.write(oprot)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.fleetMap is not None:
      oprot.writeFieldBegin('fleetMap', TType.MAP, 3)
      oprot.writeMapBegin(TType.I64, TType.STRUCT, len(self.fleetMap))
      for kiter118,viter119 in self.fleetMap.items():
        oprot.writeI64(kiter118)
        viter119.write(oprot)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.reportMap is not None:
      oprot.writeFieldBegin('reportMap', TType.MAP, 4)
      oprot.writeMapBegin(TType.I32, TType.STRUCT, len(self.reportMap))
      for kiter120,viter121 in self.reportMap.items():
        oprot.writeI32(kiter120)
        viter121.write(oprot)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.nextPlayerID is not None:
      oprot.writeFieldBegin('nextPlayerID', TType.I32, 5)
      oprot.writeI32(self.nextPlayerID)
      oprot.writeFieldEnd()
    if self.nextFleetID is not None:
      oprot.writeFieldBegin('nextFleetID', TType.I64, 6)
      oprot.writeI64(self.nextFleetID)
      oprot.writeFieldEnd()
    if self.time is not None:
      oprot.writeFieldBegin('time', TType.I32, 7)
      oprot.writeI32(self.time)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class OptionalPlayer:
  """
  Attributes:
   - player
  """

  thrift_spec = (
    None, # 0
    (1, TType.STRUCT, 'player', (Player, Player.thrift_spec), None, ), # 1
  )

  def __init__(self, player=None,):
    self.player = player

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRUCT:
          self.player = Player()
          self.player.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('OptionalPlayer')
    if self.player is not None:
      oprot.writeFieldBegin('player', TType.STRUCT, 1)
      self.player.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class TimeInfo:
  """
  Attributes:
   - roundDuration
   - univTime
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.DOUBLE, 'roundDuration', None, None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.DOUBLE, 'univTime', None, None, ), # 20
  )

  def __init__(self, roundDuration=None, univTime=None,):
    self.roundDuration = roundDuration
    self.univTime = univTime

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.DOUBLE:
          self.roundDuration = iprot.readDouble();
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.DOUBLE:
          self.univTime = iprot.readDouble();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('TimeInfo')
    if self.roundDuration is not None:
      oprot.writeFieldBegin('roundDuration', TType.DOUBLE, 10)
      oprot.writeDouble(self.roundDuration)
      oprot.writeFieldEnd()
    if self.univTime is not None:
      oprot.writeFieldBegin('univTime', TType.DOUBLE, 20)
      oprot.writeDouble(self.univTime)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class FleetList:
  """
  Attributes:
   - fleetList
   - planetList
   - fleetCount
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.LIST, 'fleetList', (TType.STRUCT,(Fleet, Fleet.thrift_spec)), None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.LIST, 'planetList', (TType.STRUCT,(Planet, Planet.thrift_spec)), None, ), # 20
    None, # 21
    None, # 22
    None, # 23
    None, # 24
    None, # 25
    None, # 26
    None, # 27
    None, # 28
    None, # 29
    (30, TType.I32, 'fleetCount', None, None, ), # 30
  )

  def __init__(self, fleetList=None, planetList=None, fleetCount=None,):
    self.fleetList = fleetList
    self.planetList = planetList
    self.fleetCount = fleetCount

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.LIST:
          self.fleetList = []
          (_etype125, _size122) = iprot.readListBegin()
          for _i126 in xrange(_size122):
            _elem127 = Fleet()
            _elem127.read(iprot)
            self.fleetList.append(_elem127)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.LIST:
          self.planetList = []
          (_etype131, _size128) = iprot.readListBegin()
          for _i132 in xrange(_size128):
            _elem133 = Planet()
            _elem133.read(iprot)
            self.planetList.append(_elem133)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 30:
        if ftype == TType.I32:
          self.fleetCount = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('FleetList')
    if self.fleetList is not None:
      oprot.writeFieldBegin('fleetList', TType.LIST, 10)
      oprot.writeListBegin(TType.STRUCT, len(self.fleetList))
      for iter134 in self.fleetList:
        iter134.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.planetList is not None:
      oprot.writeFieldBegin('planetList', TType.LIST, 20)
      oprot.writeListBegin(TType.STRUCT, len(self.planetList))
      for iter135 in self.planetList:
        iter135.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.fleetCount is not None:
      oprot.writeFieldBegin('fleetCount', TType.I32, 30)
      oprot.writeI32(self.fleetCount)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class PlanetList:
  """
  Attributes:
   - planetList
   - planetCount
  """

  thrift_spec = (
    None, # 0
    None, # 1
    None, # 2
    None, # 3
    None, # 4
    None, # 5
    None, # 6
    None, # 7
    None, # 8
    None, # 9
    (10, TType.LIST, 'planetList', (TType.STRUCT,(Planet, Planet.thrift_spec)), None, ), # 10
    None, # 11
    None, # 12
    None, # 13
    None, # 14
    None, # 15
    None, # 16
    None, # 17
    None, # 18
    None, # 19
    (20, TType.I32, 'planetCount', None, None, ), # 20
  )

  def __init__(self, planetList=None, planetCount=None,):
    self.planetList = planetList
    self.planetCount = planetCount

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 10:
        if ftype == TType.LIST:
          self.planetList = []
          (_etype139, _size136) = iprot.readListBegin()
          for _i140 in xrange(_size136):
            _elem141 = Planet()
            _elem141.read(iprot)
            self.planetList.append(_elem141)
          iprot.readListEnd()
        else:
          iprot.skip(ftype)
      elif fid == 20:
        if ftype == TType.I32:
          self.planetCount = iprot.readI32();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('PlanetList')
    if self.planetList is not None:
      oprot.writeFieldBegin('planetList', TType.LIST, 10)
      oprot.writeListBegin(TType.STRUCT, len(self.planetList))
      for iter142 in self.planetList:
        iter142.write(oprot)
      oprot.writeListEnd()
      oprot.writeFieldEnd()
    if self.planetCount is not None:
      oprot.writeFieldBegin('planetCount', TType.I32, 20)
      oprot.writeI32(self.planetCount)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
