/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EngineServer_H
#define EngineServer_H

#include <thrift/TDispatchProcessor.h>
#include "thrift_types.h"

namespace ndw
{

class EngineServerIf
{
public:
	virtual ~EngineServerIf() {}
	virtual void start() = 0;
	virtual void stop() = 0;
	virtual bool addPlayer(const std::string& login, const std::string& password) = 0;
	virtual void getPlayerFleets(FleetList& _return, const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc) = 0;
	virtual void getPlayerPlanets(PlanetList& _return, const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc) = 0;
	virtual void setPlayerFleetCode(const Player_ID pid, const std::string& code) = 0;
	virtual void setPlayerPlanetCode(const Player_ID pid, const std::string& code) = 0;
	virtual void setPlayerFleetBlocklyCode(const Player_ID pid, const std::string& code) = 0;
	virtual void setPlayerPlanetBlocklyCode(const Player_ID pid, const std::string& code) = 0;
	virtual void getPlayerFleetCode(CodeData& _return, const Player_ID pid) = 0;
	virtual void getPlayerPlanetCode(CodeData& _return, const Player_ID pid) = 0;
	virtual void getPlayers(std::vector<Player>& _return) = 0;
	virtual void getPlayer(Player& _return, const Player_ID pid) = 0;
	virtual void getPlanet(std::vector<Planet>& _return, const Coord& coord) = 0;
	virtual void getFleet(Fleet& _return, const Fleet_ID fid) = 0;
	virtual void logPlayer(OptionalPlayer& _return, const std::string& login, const std::string& password) = 0;
	virtual void incrementTutoDisplayed(const Player_ID pid, const std::string& tutoName) = 0;
	virtual void getFightReport(FightReport& _return, const int32_t id) = 0;
	virtual void getTimeInfo(TimeInfo& _return) = 0;
	virtual bool eraseAccount(const int32_t pid, const std::string& password) = 0;
	virtual void getBuildingsInfo(std::vector<Building>& _return) = 0;
	virtual void getCannonsInfo(std::vector<Cannon>& _return) = 0;
	virtual void getShipsInfo(std::vector<Ship>& _return) = 0;
};

class EngineServerIfFactory
{
public:
	typedef EngineServerIf Handler;

	virtual ~EngineServerIfFactory() {}

	virtual EngineServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
	virtual void releaseHandler(EngineServerIf* /* handler */) = 0;
};

class EngineServerIfSingletonFactory : virtual public EngineServerIfFactory
{
public:
	EngineServerIfSingletonFactory(const boost::shared_ptr<EngineServerIf>& iface) : iface_(iface) {}
	virtual ~EngineServerIfSingletonFactory() {}

	virtual EngineServerIf* getHandler(const ::apache::thrift::TConnectionInfo&)
	{
		return iface_.get();
	}
	virtual void releaseHandler(EngineServerIf* /* handler */) {}

protected:
	boost::shared_ptr<EngineServerIf> iface_;
};

class EngineServerNull : virtual public EngineServerIf
{
public:
	virtual ~EngineServerNull() {}
	void start()
	{
		return;
	}
	void stop()
	{
		return;
	}
	bool addPlayer(const std::string& /* login */, const std::string& /* password */)
	{
		bool _return = false;
		return _return;
	}
	void getPlayerFleets(FleetList& /* _return */, const Player_ID /* pid */, const int32_t /* beginIndex */, const int32_t /* endIndex */, const Sort_Type::type /* sortType */, const bool /* asc */)
	{
		return;
	}
	void getPlayerPlanets(PlanetList& /* _return */, const Player_ID /* pid */, const int32_t /* beginIndex */, const int32_t /* endIndex */, const Sort_Type::type /* sortType */, const bool /* asc */)
	{
		return;
	}
	void setPlayerFleetCode(const Player_ID /* pid */, const std::string& /* code */)
	{
		return;
	}
	void setPlayerPlanetCode(const Player_ID /* pid */, const std::string& /* code */)
	{
		return;
	}
	void setPlayerFleetBlocklyCode(const Player_ID /* pid */, const std::string& /* code */)
	{
		return;
	}
	void setPlayerPlanetBlocklyCode(const Player_ID /* pid */, const std::string& /* code */)
	{
		return;
	}
	void getPlayerFleetCode(CodeData& /* _return */, const Player_ID /* pid */)
	{
		return;
	}
	void getPlayerPlanetCode(CodeData& /* _return */, const Player_ID /* pid */)
	{
		return;
	}
	void getPlayers(std::vector<Player>& /* _return */)
	{
		return;
	}
	void getPlayer(Player& /* _return */, const Player_ID /* pid */)
	{
		return;
	}
	void getPlanet(std::vector<Planet>& /* _return */, const Coord& /* coord */)
	{
		return;
	}
	void getFleet(Fleet& /* _return */, const Fleet_ID /* fid */)
	{
		return;
	}
	void logPlayer(OptionalPlayer& /* _return */, const std::string& /* login */, const std::string& /* password */)
	{
		return;
	}
	void incrementTutoDisplayed(const Player_ID /* pid */, const std::string& /* tutoName */)
	{
		return;
	}
	void getFightReport(FightReport& /* _return */, const int32_t /* id */)
	{
		return;
	}
	void getTimeInfo(TimeInfo& /* _return */)
	{
		return;
	}
	bool eraseAccount(const int32_t /* pid */, const std::string& /* password */)
	{
		bool _return = false;
		return _return;
	}
	void getBuildingsInfo(std::vector<Building>& /* _return */)
	{
		return;
	}
	void getCannonsInfo(std::vector<Cannon>& /* _return */)
	{
		return;
	}
	void getShipsInfo(std::vector<Ship>& /* _return */)
	{
		return;
	}
};


class EngineServer_start_args
{
public:

	EngineServer_start_args()
	{
	}

	virtual ~EngineServer_start_args() throw() {}


	bool operator == (const EngineServer_start_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_start_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_start_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_start_pargs
{
public:


	virtual ~EngineServer_start_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_start_result
{
public:

	EngineServer_start_result()
	{
	}

	virtual ~EngineServer_start_result() throw() {}


	bool operator == (const EngineServer_start_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_start_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_start_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_start_presult
{
public:


	virtual ~EngineServer_start_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class EngineServer_stop_args
{
public:

	EngineServer_stop_args()
	{
	}

	virtual ~EngineServer_stop_args() throw() {}


	bool operator == (const EngineServer_stop_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_stop_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_stop_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_stop_pargs
{
public:


	virtual ~EngineServer_stop_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_stop_result
{
public:

	EngineServer_stop_result()
	{
	}

	virtual ~EngineServer_stop_result() throw() {}


	bool operator == (const EngineServer_stop_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_stop_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_stop_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_stop_presult
{
public:


	virtual ~EngineServer_stop_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_addPlayer_args__isset
{
	_EngineServer_addPlayer_args__isset() : login(false), password(false) {}
	bool login;
	bool password;
} _EngineServer_addPlayer_args__isset;

class EngineServer_addPlayer_args
{
public:

	EngineServer_addPlayer_args() : login(), password()
	{
	}

	virtual ~EngineServer_addPlayer_args() throw() {}

	std::string login;
	std::string password;

	_EngineServer_addPlayer_args__isset __isset;

	void __set_login(const std::string& val)
	{
		login = val;
	}

	void __set_password(const std::string& val)
	{
		password = val;
	}

	bool operator == (const EngineServer_addPlayer_args& rhs) const
	{
		if(!(login == rhs.login))
			return false;
		if(!(password == rhs.password))
			return false;
		return true;
	}
	bool operator != (const EngineServer_addPlayer_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_addPlayer_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_addPlayer_pargs
{
public:


	virtual ~EngineServer_addPlayer_pargs() throw() {}

	const std::string* login;
	const std::string* password;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_addPlayer_result__isset
{
	_EngineServer_addPlayer_result__isset() : success(false) {}
	bool success;
} _EngineServer_addPlayer_result__isset;

class EngineServer_addPlayer_result
{
public:

	EngineServer_addPlayer_result() : success(0)
	{
	}

	virtual ~EngineServer_addPlayer_result() throw() {}

	bool success;

	_EngineServer_addPlayer_result__isset __isset;

	void __set_success(const bool val)
	{
		success = val;
	}

	bool operator == (const EngineServer_addPlayer_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_addPlayer_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_addPlayer_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_addPlayer_presult__isset
{
	_EngineServer_addPlayer_presult__isset() : success(false) {}
	bool success;
} _EngineServer_addPlayer_presult__isset;

class EngineServer_addPlayer_presult
{
public:


	virtual ~EngineServer_addPlayer_presult() throw() {}

	bool* success;

	_EngineServer_addPlayer_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getPlayerFleets_args__isset
{
	_EngineServer_getPlayerFleets_args__isset() : pid(false), beginIndex(false), endIndex(false), sortType(false), asc(false) {}
	bool pid;
	bool beginIndex;
	bool endIndex;
	bool sortType;
	bool asc;
} _EngineServer_getPlayerFleets_args__isset;

class EngineServer_getPlayerFleets_args
{
public:

	EngineServer_getPlayerFleets_args() : pid(0), beginIndex(0), endIndex(0), sortType((Sort_Type::type)0), asc(0)
	{
	}

	virtual ~EngineServer_getPlayerFleets_args() throw() {}

	Player_ID pid;
	int32_t beginIndex;
	int32_t endIndex;
	Sort_Type::type sortType;
	bool asc;

	_EngineServer_getPlayerFleets_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_beginIndex(const int32_t val)
	{
		beginIndex = val;
	}

	void __set_endIndex(const int32_t val)
	{
		endIndex = val;
	}

	void __set_sortType(const Sort_Type::type val)
	{
		sortType = val;
	}

	void __set_asc(const bool val)
	{
		asc = val;
	}

	bool operator == (const EngineServer_getPlayerFleets_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(beginIndex == rhs.beginIndex))
			return false;
		if(!(endIndex == rhs.endIndex))
			return false;
		if(!(sortType == rhs.sortType))
			return false;
		if(!(asc == rhs.asc))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerFleets_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerFleets_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlayerFleets_pargs
{
public:


	virtual ~EngineServer_getPlayerFleets_pargs() throw() {}

	const Player_ID* pid;
	const int32_t* beginIndex;
	const int32_t* endIndex;
	const Sort_Type::type* sortType;
	const bool* asc;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerFleets_result__isset
{
	_EngineServer_getPlayerFleets_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerFleets_result__isset;

class EngineServer_getPlayerFleets_result
{
public:

	EngineServer_getPlayerFleets_result()
	{
	}

	virtual ~EngineServer_getPlayerFleets_result() throw() {}

	FleetList success;

	_EngineServer_getPlayerFleets_result__isset __isset;

	void __set_success(const FleetList& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlayerFleets_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerFleets_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerFleets_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerFleets_presult__isset
{
	_EngineServer_getPlayerFleets_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerFleets_presult__isset;

class EngineServer_getPlayerFleets_presult
{
public:


	virtual ~EngineServer_getPlayerFleets_presult() throw() {}

	FleetList* success;

	_EngineServer_getPlayerFleets_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getPlayerPlanets_args__isset
{
	_EngineServer_getPlayerPlanets_args__isset() : pid(false), beginIndex(false), endIndex(false), sortType(false), asc(false) {}
	bool pid;
	bool beginIndex;
	bool endIndex;
	bool sortType;
	bool asc;
} _EngineServer_getPlayerPlanets_args__isset;

class EngineServer_getPlayerPlanets_args
{
public:

	EngineServer_getPlayerPlanets_args() : pid(0), beginIndex(0), endIndex(0), sortType((Sort_Type::type)0), asc(0)
	{
	}

	virtual ~EngineServer_getPlayerPlanets_args() throw() {}

	Player_ID pid;
	int32_t beginIndex;
	int32_t endIndex;
	Sort_Type::type sortType;
	bool asc;

	_EngineServer_getPlayerPlanets_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_beginIndex(const int32_t val)
	{
		beginIndex = val;
	}

	void __set_endIndex(const int32_t val)
	{
		endIndex = val;
	}

	void __set_sortType(const Sort_Type::type val)
	{
		sortType = val;
	}

	void __set_asc(const bool val)
	{
		asc = val;
	}

	bool operator == (const EngineServer_getPlayerPlanets_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(beginIndex == rhs.beginIndex))
			return false;
		if(!(endIndex == rhs.endIndex))
			return false;
		if(!(sortType == rhs.sortType))
			return false;
		if(!(asc == rhs.asc))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerPlanets_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerPlanets_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlayerPlanets_pargs
{
public:


	virtual ~EngineServer_getPlayerPlanets_pargs() throw() {}

	const Player_ID* pid;
	const int32_t* beginIndex;
	const int32_t* endIndex;
	const Sort_Type::type* sortType;
	const bool* asc;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerPlanets_result__isset
{
	_EngineServer_getPlayerPlanets_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerPlanets_result__isset;

class EngineServer_getPlayerPlanets_result
{
public:

	EngineServer_getPlayerPlanets_result()
	{
	}

	virtual ~EngineServer_getPlayerPlanets_result() throw() {}

	PlanetList success;

	_EngineServer_getPlayerPlanets_result__isset __isset;

	void __set_success(const PlanetList& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlayerPlanets_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerPlanets_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerPlanets_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerPlanets_presult__isset
{
	_EngineServer_getPlayerPlanets_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerPlanets_presult__isset;

class EngineServer_getPlayerPlanets_presult
{
public:


	virtual ~EngineServer_getPlayerPlanets_presult() throw() {}

	PlanetList* success;

	_EngineServer_getPlayerPlanets_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_setPlayerFleetCode_args__isset
{
	_EngineServer_setPlayerFleetCode_args__isset() : pid(false), code(false) {}
	bool pid;
	bool code;
} _EngineServer_setPlayerFleetCode_args__isset;

class EngineServer_setPlayerFleetCode_args
{
public:

	EngineServer_setPlayerFleetCode_args() : pid(0), code()
	{
	}

	virtual ~EngineServer_setPlayerFleetCode_args() throw() {}

	Player_ID pid;
	std::string code;

	_EngineServer_setPlayerFleetCode_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_code(const std::string& val)
	{
		code = val;
	}

	bool operator == (const EngineServer_setPlayerFleetCode_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(code == rhs.code))
			return false;
		return true;
	}
	bool operator != (const EngineServer_setPlayerFleetCode_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerFleetCode_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerFleetCode_pargs
{
public:


	virtual ~EngineServer_setPlayerFleetCode_pargs() throw() {}

	const Player_ID* pid;
	const std::string* code;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerFleetCode_result
{
public:

	EngineServer_setPlayerFleetCode_result()
	{
	}

	virtual ~EngineServer_setPlayerFleetCode_result() throw() {}


	bool operator == (const EngineServer_setPlayerFleetCode_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_setPlayerFleetCode_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerFleetCode_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerFleetCode_presult
{
public:


	virtual ~EngineServer_setPlayerFleetCode_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_setPlayerPlanetCode_args__isset
{
	_EngineServer_setPlayerPlanetCode_args__isset() : pid(false), code(false) {}
	bool pid;
	bool code;
} _EngineServer_setPlayerPlanetCode_args__isset;

class EngineServer_setPlayerPlanetCode_args
{
public:

	EngineServer_setPlayerPlanetCode_args() : pid(0), code()
	{
	}

	virtual ~EngineServer_setPlayerPlanetCode_args() throw() {}

	Player_ID pid;
	std::string code;

	_EngineServer_setPlayerPlanetCode_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_code(const std::string& val)
	{
		code = val;
	}

	bool operator == (const EngineServer_setPlayerPlanetCode_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(code == rhs.code))
			return false;
		return true;
	}
	bool operator != (const EngineServer_setPlayerPlanetCode_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerPlanetCode_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerPlanetCode_pargs
{
public:


	virtual ~EngineServer_setPlayerPlanetCode_pargs() throw() {}

	const Player_ID* pid;
	const std::string* code;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerPlanetCode_result
{
public:

	EngineServer_setPlayerPlanetCode_result()
	{
	}

	virtual ~EngineServer_setPlayerPlanetCode_result() throw() {}


	bool operator == (const EngineServer_setPlayerPlanetCode_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_setPlayerPlanetCode_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerPlanetCode_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerPlanetCode_presult
{
public:


	virtual ~EngineServer_setPlayerPlanetCode_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_setPlayerFleetBlocklyCode_args__isset
{
	_EngineServer_setPlayerFleetBlocklyCode_args__isset() : pid(false), code(false) {}
	bool pid;
	bool code;
} _EngineServer_setPlayerFleetBlocklyCode_args__isset;

class EngineServer_setPlayerFleetBlocklyCode_args
{
public:

	EngineServer_setPlayerFleetBlocklyCode_args() : pid(0), code()
	{
	}

	virtual ~EngineServer_setPlayerFleetBlocklyCode_args() throw() {}

	Player_ID pid;
	std::string code;

	_EngineServer_setPlayerFleetBlocklyCode_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_code(const std::string& val)
	{
		code = val;
	}

	bool operator == (const EngineServer_setPlayerFleetBlocklyCode_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(code == rhs.code))
			return false;
		return true;
	}
	bool operator != (const EngineServer_setPlayerFleetBlocklyCode_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerFleetBlocklyCode_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerFleetBlocklyCode_pargs
{
public:


	virtual ~EngineServer_setPlayerFleetBlocklyCode_pargs() throw() {}

	const Player_ID* pid;
	const std::string* code;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerFleetBlocklyCode_result
{
public:

	EngineServer_setPlayerFleetBlocklyCode_result()
	{
	}

	virtual ~EngineServer_setPlayerFleetBlocklyCode_result() throw() {}


	bool operator == (const EngineServer_setPlayerFleetBlocklyCode_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_setPlayerFleetBlocklyCode_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerFleetBlocklyCode_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerFleetBlocklyCode_presult
{
public:


	virtual ~EngineServer_setPlayerFleetBlocklyCode_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_setPlayerPlanetBlocklyCode_args__isset
{
	_EngineServer_setPlayerPlanetBlocklyCode_args__isset() : pid(false), code(false) {}
	bool pid;
	bool code;
} _EngineServer_setPlayerPlanetBlocklyCode_args__isset;

class EngineServer_setPlayerPlanetBlocklyCode_args
{
public:

	EngineServer_setPlayerPlanetBlocklyCode_args() : pid(0), code()
	{
	}

	virtual ~EngineServer_setPlayerPlanetBlocklyCode_args() throw() {}

	Player_ID pid;
	std::string code;

	_EngineServer_setPlayerPlanetBlocklyCode_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_code(const std::string& val)
	{
		code = val;
	}

	bool operator == (const EngineServer_setPlayerPlanetBlocklyCode_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(code == rhs.code))
			return false;
		return true;
	}
	bool operator != (const EngineServer_setPlayerPlanetBlocklyCode_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerPlanetBlocklyCode_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerPlanetBlocklyCode_pargs
{
public:


	virtual ~EngineServer_setPlayerPlanetBlocklyCode_pargs() throw() {}

	const Player_ID* pid;
	const std::string* code;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerPlanetBlocklyCode_result
{
public:

	EngineServer_setPlayerPlanetBlocklyCode_result()
	{
	}

	virtual ~EngineServer_setPlayerPlanetBlocklyCode_result() throw() {}


	bool operator == (const EngineServer_setPlayerPlanetBlocklyCode_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_setPlayerPlanetBlocklyCode_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_setPlayerPlanetBlocklyCode_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_setPlayerPlanetBlocklyCode_presult
{
public:


	virtual ~EngineServer_setPlayerPlanetBlocklyCode_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getPlayerFleetCode_args__isset
{
	_EngineServer_getPlayerFleetCode_args__isset() : pid(false) {}
	bool pid;
} _EngineServer_getPlayerFleetCode_args__isset;

class EngineServer_getPlayerFleetCode_args
{
public:

	EngineServer_getPlayerFleetCode_args() : pid(0)
	{
	}

	virtual ~EngineServer_getPlayerFleetCode_args() throw() {}

	Player_ID pid;

	_EngineServer_getPlayerFleetCode_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	bool operator == (const EngineServer_getPlayerFleetCode_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerFleetCode_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerFleetCode_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlayerFleetCode_pargs
{
public:


	virtual ~EngineServer_getPlayerFleetCode_pargs() throw() {}

	const Player_ID* pid;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerFleetCode_result__isset
{
	_EngineServer_getPlayerFleetCode_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerFleetCode_result__isset;

class EngineServer_getPlayerFleetCode_result
{
public:

	EngineServer_getPlayerFleetCode_result()
	{
	}

	virtual ~EngineServer_getPlayerFleetCode_result() throw() {}

	CodeData success;

	_EngineServer_getPlayerFleetCode_result__isset __isset;

	void __set_success(const CodeData& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlayerFleetCode_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerFleetCode_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerFleetCode_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerFleetCode_presult__isset
{
	_EngineServer_getPlayerFleetCode_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerFleetCode_presult__isset;

class EngineServer_getPlayerFleetCode_presult
{
public:


	virtual ~EngineServer_getPlayerFleetCode_presult() throw() {}

	CodeData* success;

	_EngineServer_getPlayerFleetCode_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getPlayerPlanetCode_args__isset
{
	_EngineServer_getPlayerPlanetCode_args__isset() : pid(false) {}
	bool pid;
} _EngineServer_getPlayerPlanetCode_args__isset;

class EngineServer_getPlayerPlanetCode_args
{
public:

	EngineServer_getPlayerPlanetCode_args() : pid(0)
	{
	}

	virtual ~EngineServer_getPlayerPlanetCode_args() throw() {}

	Player_ID pid;

	_EngineServer_getPlayerPlanetCode_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	bool operator == (const EngineServer_getPlayerPlanetCode_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerPlanetCode_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerPlanetCode_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlayerPlanetCode_pargs
{
public:


	virtual ~EngineServer_getPlayerPlanetCode_pargs() throw() {}

	const Player_ID* pid;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerPlanetCode_result__isset
{
	_EngineServer_getPlayerPlanetCode_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerPlanetCode_result__isset;

class EngineServer_getPlayerPlanetCode_result
{
public:

	EngineServer_getPlayerPlanetCode_result()
	{
	}

	virtual ~EngineServer_getPlayerPlanetCode_result() throw() {}

	CodeData success;

	_EngineServer_getPlayerPlanetCode_result__isset __isset;

	void __set_success(const CodeData& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlayerPlanetCode_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayerPlanetCode_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayerPlanetCode_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayerPlanetCode_presult__isset
{
	_EngineServer_getPlayerPlanetCode_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayerPlanetCode_presult__isset;

class EngineServer_getPlayerPlanetCode_presult
{
public:


	virtual ~EngineServer_getPlayerPlanetCode_presult() throw() {}

	CodeData* success;

	_EngineServer_getPlayerPlanetCode_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class EngineServer_getPlayers_args
{
public:

	EngineServer_getPlayers_args()
	{
	}

	virtual ~EngineServer_getPlayers_args() throw() {}


	bool operator == (const EngineServer_getPlayers_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_getPlayers_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayers_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlayers_pargs
{
public:


	virtual ~EngineServer_getPlayers_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayers_result__isset
{
	_EngineServer_getPlayers_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayers_result__isset;

class EngineServer_getPlayers_result
{
public:

	EngineServer_getPlayers_result()
	{
	}

	virtual ~EngineServer_getPlayers_result() throw() {}

	std::vector<Player>  success;

	_EngineServer_getPlayers_result__isset __isset;

	void __set_success(const std::vector<Player>& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlayers_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayers_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayers_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayers_presult__isset
{
	_EngineServer_getPlayers_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayers_presult__isset;

class EngineServer_getPlayers_presult
{
public:


	virtual ~EngineServer_getPlayers_presult() throw() {}

	std::vector<Player>* success;

	_EngineServer_getPlayers_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getPlayer_args__isset
{
	_EngineServer_getPlayer_args__isset() : pid(false) {}
	bool pid;
} _EngineServer_getPlayer_args__isset;

class EngineServer_getPlayer_args
{
public:

	EngineServer_getPlayer_args() : pid(0)
	{
	}

	virtual ~EngineServer_getPlayer_args() throw() {}

	Player_ID pid;

	_EngineServer_getPlayer_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	bool operator == (const EngineServer_getPlayer_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayer_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayer_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlayer_pargs
{
public:


	virtual ~EngineServer_getPlayer_pargs() throw() {}

	const Player_ID* pid;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayer_result__isset
{
	_EngineServer_getPlayer_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayer_result__isset;

class EngineServer_getPlayer_result
{
public:

	EngineServer_getPlayer_result()
	{
	}

	virtual ~EngineServer_getPlayer_result() throw() {}

	Player success;

	_EngineServer_getPlayer_result__isset __isset;

	void __set_success(const Player& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlayer_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlayer_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlayer_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlayer_presult__isset
{
	_EngineServer_getPlayer_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlayer_presult__isset;

class EngineServer_getPlayer_presult
{
public:


	virtual ~EngineServer_getPlayer_presult() throw() {}

	Player* success;

	_EngineServer_getPlayer_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getPlanet_args__isset
{
	_EngineServer_getPlanet_args__isset() : coord(false) {}
	bool coord;
} _EngineServer_getPlanet_args__isset;

class EngineServer_getPlanet_args
{
public:

	EngineServer_getPlanet_args()
	{
	}

	virtual ~EngineServer_getPlanet_args() throw() {}

	Coord coord;

	_EngineServer_getPlanet_args__isset __isset;

	void __set_coord(const Coord& val)
	{
		coord = val;
	}

	bool operator == (const EngineServer_getPlanet_args& rhs) const
	{
		if(!(coord == rhs.coord))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlanet_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlanet_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getPlanet_pargs
{
public:


	virtual ~EngineServer_getPlanet_pargs() throw() {}

	const Coord* coord;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlanet_result__isset
{
	_EngineServer_getPlanet_result__isset() : success(false) {}
	bool success;
} _EngineServer_getPlanet_result__isset;

class EngineServer_getPlanet_result
{
public:

	EngineServer_getPlanet_result()
	{
	}

	virtual ~EngineServer_getPlanet_result() throw() {}

	std::vector<Planet>  success;

	_EngineServer_getPlanet_result__isset __isset;

	void __set_success(const std::vector<Planet>& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getPlanet_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getPlanet_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getPlanet_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getPlanet_presult__isset
{
	_EngineServer_getPlanet_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getPlanet_presult__isset;

class EngineServer_getPlanet_presult
{
public:


	virtual ~EngineServer_getPlanet_presult() throw() {}

	std::vector<Planet>* success;

	_EngineServer_getPlanet_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getFleet_args__isset
{
	_EngineServer_getFleet_args__isset() : fid(false) {}
	bool fid;
} _EngineServer_getFleet_args__isset;

class EngineServer_getFleet_args
{
public:

	EngineServer_getFleet_args() : fid(0)
	{
	}

	virtual ~EngineServer_getFleet_args() throw() {}

	Fleet_ID fid;

	_EngineServer_getFleet_args__isset __isset;

	void __set_fid(const Fleet_ID val)
	{
		fid = val;
	}

	bool operator == (const EngineServer_getFleet_args& rhs) const
	{
		if(!(fid == rhs.fid))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getFleet_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getFleet_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getFleet_pargs
{
public:


	virtual ~EngineServer_getFleet_pargs() throw() {}

	const Fleet_ID* fid;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getFleet_result__isset
{
	_EngineServer_getFleet_result__isset() : success(false) {}
	bool success;
} _EngineServer_getFleet_result__isset;

class EngineServer_getFleet_result
{
public:

	EngineServer_getFleet_result()
	{
	}

	virtual ~EngineServer_getFleet_result() throw() {}

	Fleet success;

	_EngineServer_getFleet_result__isset __isset;

	void __set_success(const Fleet& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getFleet_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getFleet_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getFleet_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getFleet_presult__isset
{
	_EngineServer_getFleet_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getFleet_presult__isset;

class EngineServer_getFleet_presult
{
public:


	virtual ~EngineServer_getFleet_presult() throw() {}

	Fleet* success;

	_EngineServer_getFleet_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_logPlayer_args__isset
{
	_EngineServer_logPlayer_args__isset() : login(false), password(false) {}
	bool login;
	bool password;
} _EngineServer_logPlayer_args__isset;

class EngineServer_logPlayer_args
{
public:

	EngineServer_logPlayer_args() : login(), password()
	{
	}

	virtual ~EngineServer_logPlayer_args() throw() {}

	std::string login;
	std::string password;

	_EngineServer_logPlayer_args__isset __isset;

	void __set_login(const std::string& val)
	{
		login = val;
	}

	void __set_password(const std::string& val)
	{
		password = val;
	}

	bool operator == (const EngineServer_logPlayer_args& rhs) const
	{
		if(!(login == rhs.login))
			return false;
		if(!(password == rhs.password))
			return false;
		return true;
	}
	bool operator != (const EngineServer_logPlayer_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_logPlayer_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_logPlayer_pargs
{
public:


	virtual ~EngineServer_logPlayer_pargs() throw() {}

	const std::string* login;
	const std::string* password;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_logPlayer_result__isset
{
	_EngineServer_logPlayer_result__isset() : success(false) {}
	bool success;
} _EngineServer_logPlayer_result__isset;

class EngineServer_logPlayer_result
{
public:

	EngineServer_logPlayer_result()
	{
	}

	virtual ~EngineServer_logPlayer_result() throw() {}

	OptionalPlayer success;

	_EngineServer_logPlayer_result__isset __isset;

	void __set_success(const OptionalPlayer& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_logPlayer_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_logPlayer_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_logPlayer_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_logPlayer_presult__isset
{
	_EngineServer_logPlayer_presult__isset() : success(false) {}
	bool success;
} _EngineServer_logPlayer_presult__isset;

class EngineServer_logPlayer_presult
{
public:


	virtual ~EngineServer_logPlayer_presult() throw() {}

	OptionalPlayer* success;

	_EngineServer_logPlayer_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_incrementTutoDisplayed_args__isset
{
	_EngineServer_incrementTutoDisplayed_args__isset() : pid(false), tutoName(false) {}
	bool pid;
	bool tutoName;
} _EngineServer_incrementTutoDisplayed_args__isset;

class EngineServer_incrementTutoDisplayed_args
{
public:

	EngineServer_incrementTutoDisplayed_args() : pid(0), tutoName()
	{
	}

	virtual ~EngineServer_incrementTutoDisplayed_args() throw() {}

	Player_ID pid;
	std::string tutoName;

	_EngineServer_incrementTutoDisplayed_args__isset __isset;

	void __set_pid(const Player_ID val)
	{
		pid = val;
	}

	void __set_tutoName(const std::string& val)
	{
		tutoName = val;
	}

	bool operator == (const EngineServer_incrementTutoDisplayed_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(tutoName == rhs.tutoName))
			return false;
		return true;
	}
	bool operator != (const EngineServer_incrementTutoDisplayed_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_incrementTutoDisplayed_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_incrementTutoDisplayed_pargs
{
public:


	virtual ~EngineServer_incrementTutoDisplayed_pargs() throw() {}

	const Player_ID* pid;
	const std::string* tutoName;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_incrementTutoDisplayed_result
{
public:

	EngineServer_incrementTutoDisplayed_result()
	{
	}

	virtual ~EngineServer_incrementTutoDisplayed_result() throw() {}


	bool operator == (const EngineServer_incrementTutoDisplayed_result& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_incrementTutoDisplayed_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_incrementTutoDisplayed_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_incrementTutoDisplayed_presult
{
public:


	virtual ~EngineServer_incrementTutoDisplayed_presult() throw() {}


	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_getFightReport_args__isset
{
	_EngineServer_getFightReport_args__isset() : id(false) {}
	bool id;
} _EngineServer_getFightReport_args__isset;

class EngineServer_getFightReport_args
{
public:

	EngineServer_getFightReport_args() : id(0)
	{
	}

	virtual ~EngineServer_getFightReport_args() throw() {}

	int32_t id;

	_EngineServer_getFightReport_args__isset __isset;

	void __set_id(const int32_t val)
	{
		id = val;
	}

	bool operator == (const EngineServer_getFightReport_args& rhs) const
	{
		if(!(id == rhs.id))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getFightReport_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getFightReport_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getFightReport_pargs
{
public:


	virtual ~EngineServer_getFightReport_pargs() throw() {}

	const int32_t* id;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getFightReport_result__isset
{
	_EngineServer_getFightReport_result__isset() : success(false) {}
	bool success;
} _EngineServer_getFightReport_result__isset;

class EngineServer_getFightReport_result
{
public:

	EngineServer_getFightReport_result()
	{
	}

	virtual ~EngineServer_getFightReport_result() throw() {}

	FightReport success;

	_EngineServer_getFightReport_result__isset __isset;

	void __set_success(const FightReport& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getFightReport_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getFightReport_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getFightReport_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getFightReport_presult__isset
{
	_EngineServer_getFightReport_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getFightReport_presult__isset;

class EngineServer_getFightReport_presult
{
public:


	virtual ~EngineServer_getFightReport_presult() throw() {}

	FightReport* success;

	_EngineServer_getFightReport_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class EngineServer_getTimeInfo_args
{
public:

	EngineServer_getTimeInfo_args()
	{
	}

	virtual ~EngineServer_getTimeInfo_args() throw() {}


	bool operator == (const EngineServer_getTimeInfo_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_getTimeInfo_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getTimeInfo_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getTimeInfo_pargs
{
public:


	virtual ~EngineServer_getTimeInfo_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getTimeInfo_result__isset
{
	_EngineServer_getTimeInfo_result__isset() : success(false) {}
	bool success;
} _EngineServer_getTimeInfo_result__isset;

class EngineServer_getTimeInfo_result
{
public:

	EngineServer_getTimeInfo_result()
	{
	}

	virtual ~EngineServer_getTimeInfo_result() throw() {}

	TimeInfo success;

	_EngineServer_getTimeInfo_result__isset __isset;

	void __set_success(const TimeInfo& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getTimeInfo_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getTimeInfo_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getTimeInfo_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getTimeInfo_presult__isset
{
	_EngineServer_getTimeInfo_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getTimeInfo_presult__isset;

class EngineServer_getTimeInfo_presult
{
public:


	virtual ~EngineServer_getTimeInfo_presult() throw() {}

	TimeInfo* success;

	_EngineServer_getTimeInfo_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineServer_eraseAccount_args__isset
{
	_EngineServer_eraseAccount_args__isset() : pid(false), password(false) {}
	bool pid;
	bool password;
} _EngineServer_eraseAccount_args__isset;

class EngineServer_eraseAccount_args
{
public:

	EngineServer_eraseAccount_args() : pid(0), password()
	{
	}

	virtual ~EngineServer_eraseAccount_args() throw() {}

	int32_t pid;
	std::string password;

	_EngineServer_eraseAccount_args__isset __isset;

	void __set_pid(const int32_t val)
	{
		pid = val;
	}

	void __set_password(const std::string& val)
	{
		password = val;
	}

	bool operator == (const EngineServer_eraseAccount_args& rhs) const
	{
		if(!(pid == rhs.pid))
			return false;
		if(!(password == rhs.password))
			return false;
		return true;
	}
	bool operator != (const EngineServer_eraseAccount_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_eraseAccount_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_eraseAccount_pargs
{
public:


	virtual ~EngineServer_eraseAccount_pargs() throw() {}

	const int32_t* pid;
	const std::string* password;

	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_eraseAccount_result__isset
{
	_EngineServer_eraseAccount_result__isset() : success(false) {}
	bool success;
} _EngineServer_eraseAccount_result__isset;

class EngineServer_eraseAccount_result
{
public:

	EngineServer_eraseAccount_result() : success(0)
	{
	}

	virtual ~EngineServer_eraseAccount_result() throw() {}

	bool success;

	_EngineServer_eraseAccount_result__isset __isset;

	void __set_success(const bool val)
	{
		success = val;
	}

	bool operator == (const EngineServer_eraseAccount_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_eraseAccount_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_eraseAccount_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_eraseAccount_presult__isset
{
	_EngineServer_eraseAccount_presult__isset() : success(false) {}
	bool success;
} _EngineServer_eraseAccount_presult__isset;

class EngineServer_eraseAccount_presult
{
public:


	virtual ~EngineServer_eraseAccount_presult() throw() {}

	bool* success;

	_EngineServer_eraseAccount_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class EngineServer_getBuildingsInfo_args
{
public:

	EngineServer_getBuildingsInfo_args()
	{
	}

	virtual ~EngineServer_getBuildingsInfo_args() throw() {}


	bool operator == (const EngineServer_getBuildingsInfo_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_getBuildingsInfo_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getBuildingsInfo_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getBuildingsInfo_pargs
{
public:


	virtual ~EngineServer_getBuildingsInfo_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getBuildingsInfo_result__isset
{
	_EngineServer_getBuildingsInfo_result__isset() : success(false) {}
	bool success;
} _EngineServer_getBuildingsInfo_result__isset;

class EngineServer_getBuildingsInfo_result
{
public:

	EngineServer_getBuildingsInfo_result()
	{
	}

	virtual ~EngineServer_getBuildingsInfo_result() throw() {}

	std::vector<Building>  success;

	_EngineServer_getBuildingsInfo_result__isset __isset;

	void __set_success(const std::vector<Building>& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getBuildingsInfo_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getBuildingsInfo_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getBuildingsInfo_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getBuildingsInfo_presult__isset
{
	_EngineServer_getBuildingsInfo_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getBuildingsInfo_presult__isset;

class EngineServer_getBuildingsInfo_presult
{
public:


	virtual ~EngineServer_getBuildingsInfo_presult() throw() {}

	std::vector<Building>* success;

	_EngineServer_getBuildingsInfo_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class EngineServer_getCannonsInfo_args
{
public:

	EngineServer_getCannonsInfo_args()
	{
	}

	virtual ~EngineServer_getCannonsInfo_args() throw() {}


	bool operator == (const EngineServer_getCannonsInfo_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_getCannonsInfo_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getCannonsInfo_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getCannonsInfo_pargs
{
public:


	virtual ~EngineServer_getCannonsInfo_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getCannonsInfo_result__isset
{
	_EngineServer_getCannonsInfo_result__isset() : success(false) {}
	bool success;
} _EngineServer_getCannonsInfo_result__isset;

class EngineServer_getCannonsInfo_result
{
public:

	EngineServer_getCannonsInfo_result()
	{
	}

	virtual ~EngineServer_getCannonsInfo_result() throw() {}

	std::vector<Cannon>  success;

	_EngineServer_getCannonsInfo_result__isset __isset;

	void __set_success(const std::vector<Cannon>& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getCannonsInfo_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getCannonsInfo_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getCannonsInfo_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getCannonsInfo_presult__isset
{
	_EngineServer_getCannonsInfo_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getCannonsInfo_presult__isset;

class EngineServer_getCannonsInfo_presult
{
public:


	virtual ~EngineServer_getCannonsInfo_presult() throw() {}

	std::vector<Cannon>* success;

	_EngineServer_getCannonsInfo_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class EngineServer_getShipsInfo_args
{
public:

	EngineServer_getShipsInfo_args()
	{
	}

	virtual ~EngineServer_getShipsInfo_args() throw() {}


	bool operator == (const EngineServer_getShipsInfo_args& /* rhs */) const
	{
		return true;
	}
	bool operator != (const EngineServer_getShipsInfo_args& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getShipsInfo_args&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineServer_getShipsInfo_pargs
{
public:


	virtual ~EngineServer_getShipsInfo_pargs() throw() {}


	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getShipsInfo_result__isset
{
	_EngineServer_getShipsInfo_result__isset() : success(false) {}
	bool success;
} _EngineServer_getShipsInfo_result__isset;

class EngineServer_getShipsInfo_result
{
public:

	EngineServer_getShipsInfo_result()
	{
	}

	virtual ~EngineServer_getShipsInfo_result() throw() {}

	std::vector<Ship>  success;

	_EngineServer_getShipsInfo_result__isset __isset;

	void __set_success(const std::vector<Ship>& val)
	{
		success = val;
	}

	bool operator == (const EngineServer_getShipsInfo_result& rhs) const
	{
		if(!(success == rhs.success))
			return false;
		return true;
	}
	bool operator != (const EngineServer_getShipsInfo_result& rhs) const
	{
		return !(*this == rhs);
	}

	bool operator < (const EngineServer_getShipsInfo_result&) const;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
	uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineServer_getShipsInfo_presult__isset
{
	_EngineServer_getShipsInfo_presult__isset() : success(false) {}
	bool success;
} _EngineServer_getShipsInfo_presult__isset;

class EngineServer_getShipsInfo_presult
{
public:


	virtual ~EngineServer_getShipsInfo_presult() throw() {}

	std::vector<Ship>* success;

	_EngineServer_getShipsInfo_presult__isset __isset;

	uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class EngineServerClient : virtual public EngineServerIf
{
public:
	EngineServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
		piprot_(prot),
		poprot_(prot)
	{
		iprot_ = prot.get();
		oprot_ = prot.get();
	}
	EngineServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
		piprot_(iprot),
		poprot_(oprot)
	{
		iprot_ = iprot.get();
		oprot_ = oprot.get();
	}
	boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol()
	{
		return piprot_;
	}
	boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol()
	{
		return poprot_;
	}
	void start();
	void send_start();
	void recv_start();
	void stop();
	void send_stop();
	void recv_stop();
	bool addPlayer(const std::string& login, const std::string& password);
	void send_addPlayer(const std::string& login, const std::string& password);
	bool recv_addPlayer();
	void getPlayerFleets(FleetList& _return, const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc);
	void send_getPlayerFleets(const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc);
	void recv_getPlayerFleets(FleetList& _return);
	void getPlayerPlanets(PlanetList& _return, const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc);
	void send_getPlayerPlanets(const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc);
	void recv_getPlayerPlanets(PlanetList& _return);
	void setPlayerFleetCode(const Player_ID pid, const std::string& code);
	void send_setPlayerFleetCode(const Player_ID pid, const std::string& code);
	void recv_setPlayerFleetCode();
	void setPlayerPlanetCode(const Player_ID pid, const std::string& code);
	void send_setPlayerPlanetCode(const Player_ID pid, const std::string& code);
	void recv_setPlayerPlanetCode();
	void setPlayerFleetBlocklyCode(const Player_ID pid, const std::string& code);
	void send_setPlayerFleetBlocklyCode(const Player_ID pid, const std::string& code);
	void recv_setPlayerFleetBlocklyCode();
	void setPlayerPlanetBlocklyCode(const Player_ID pid, const std::string& code);
	void send_setPlayerPlanetBlocklyCode(const Player_ID pid, const std::string& code);
	void recv_setPlayerPlanetBlocklyCode();
	void getPlayerFleetCode(CodeData& _return, const Player_ID pid);
	void send_getPlayerFleetCode(const Player_ID pid);
	void recv_getPlayerFleetCode(CodeData& _return);
	void getPlayerPlanetCode(CodeData& _return, const Player_ID pid);
	void send_getPlayerPlanetCode(const Player_ID pid);
	void recv_getPlayerPlanetCode(CodeData& _return);
	void getPlayers(std::vector<Player>& _return);
	void send_getPlayers();
	void recv_getPlayers(std::vector<Player>& _return);
	void getPlayer(Player& _return, const Player_ID pid);
	void send_getPlayer(const Player_ID pid);
	void recv_getPlayer(Player& _return);
	void getPlanet(std::vector<Planet>& _return, const Coord& coord);
	void send_getPlanet(const Coord& coord);
	void recv_getPlanet(std::vector<Planet>& _return);
	void getFleet(Fleet& _return, const Fleet_ID fid);
	void send_getFleet(const Fleet_ID fid);
	void recv_getFleet(Fleet& _return);
	void logPlayer(OptionalPlayer& _return, const std::string& login, const std::string& password);
	void send_logPlayer(const std::string& login, const std::string& password);
	void recv_logPlayer(OptionalPlayer& _return);
	void incrementTutoDisplayed(const Player_ID pid, const std::string& tutoName);
	void send_incrementTutoDisplayed(const Player_ID pid, const std::string& tutoName);
	void recv_incrementTutoDisplayed();
	void getFightReport(FightReport& _return, const int32_t id);
	void send_getFightReport(const int32_t id);
	void recv_getFightReport(FightReport& _return);
	void getTimeInfo(TimeInfo& _return);
	void send_getTimeInfo();
	void recv_getTimeInfo(TimeInfo& _return);
	bool eraseAccount(const int32_t pid, const std::string& password);
	void send_eraseAccount(const int32_t pid, const std::string& password);
	bool recv_eraseAccount();
	void getBuildingsInfo(std::vector<Building>& _return);
	void send_getBuildingsInfo();
	void recv_getBuildingsInfo(std::vector<Building>& _return);
	void getCannonsInfo(std::vector<Cannon>& _return);
	void send_getCannonsInfo();
	void recv_getCannonsInfo(std::vector<Cannon>& _return);
	void getShipsInfo(std::vector<Ship>& _return);
	void send_getShipsInfo();
	void recv_getShipsInfo(std::vector<Ship>& _return);
protected:
	boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
	boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
	::apache::thrift::protocol::TProtocol* iprot_;
	::apache::thrift::protocol::TProtocol* oprot_;
};

class EngineServerProcessor : public ::apache::thrift::TDispatchProcessor
{
protected:
	boost::shared_ptr<EngineServerIf> iface_;
	virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
private:
	typedef  void (EngineServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
	typedef std::map<std::string, ProcessFunction> ProcessMap;
	ProcessMap processMap_;
	void process_start(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_stop(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_addPlayer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlayerFleets(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlayerPlanets(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_setPlayerFleetCode(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_setPlayerPlanetCode(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_setPlayerFleetBlocklyCode(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_setPlayerPlanetBlocklyCode(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlayerFleetCode(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlayerPlanetCode(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlayers(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlayer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getPlanet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getFleet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_logPlayer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_incrementTutoDisplayed(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getFightReport(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getTimeInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_eraseAccount(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getBuildingsInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getCannonsInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
	void process_getShipsInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
public:
	EngineServerProcessor(boost::shared_ptr<EngineServerIf> iface) :
		iface_(iface)
	{
		processMap_["start"] = &EngineServerProcessor::process_start;
		processMap_["stop"] = &EngineServerProcessor::process_stop;
		processMap_["addPlayer"] = &EngineServerProcessor::process_addPlayer;
		processMap_["getPlayerFleets"] = &EngineServerProcessor::process_getPlayerFleets;
		processMap_["getPlayerPlanets"] = &EngineServerProcessor::process_getPlayerPlanets;
		processMap_["setPlayerFleetCode"] = &EngineServerProcessor::process_setPlayerFleetCode;
		processMap_["setPlayerPlanetCode"] = &EngineServerProcessor::process_setPlayerPlanetCode;
		processMap_["setPlayerFleetBlocklyCode"] = &EngineServerProcessor::process_setPlayerFleetBlocklyCode;
		processMap_["setPlayerPlanetBlocklyCode"] = &EngineServerProcessor::process_setPlayerPlanetBlocklyCode;
		processMap_["getPlayerFleetCode"] = &EngineServerProcessor::process_getPlayerFleetCode;
		processMap_["getPlayerPlanetCode"] = &EngineServerProcessor::process_getPlayerPlanetCode;
		processMap_["getPlayers"] = &EngineServerProcessor::process_getPlayers;
		processMap_["getPlayer"] = &EngineServerProcessor::process_getPlayer;
		processMap_["getPlanet"] = &EngineServerProcessor::process_getPlanet;
		processMap_["getFleet"] = &EngineServerProcessor::process_getFleet;
		processMap_["logPlayer"] = &EngineServerProcessor::process_logPlayer;
		processMap_["incrementTutoDisplayed"] = &EngineServerProcessor::process_incrementTutoDisplayed;
		processMap_["getFightReport"] = &EngineServerProcessor::process_getFightReport;
		processMap_["getTimeInfo"] = &EngineServerProcessor::process_getTimeInfo;
		processMap_["eraseAccount"] = &EngineServerProcessor::process_eraseAccount;
		processMap_["getBuildingsInfo"] = &EngineServerProcessor::process_getBuildingsInfo;
		processMap_["getCannonsInfo"] = &EngineServerProcessor::process_getCannonsInfo;
		processMap_["getShipsInfo"] = &EngineServerProcessor::process_getShipsInfo;
	}

	virtual ~EngineServerProcessor() {}
};

class EngineServerProcessorFactory : public ::apache::thrift::TProcessorFactory
{
public:
	EngineServerProcessorFactory(const ::boost::shared_ptr< EngineServerIfFactory >& handlerFactory) :
		handlerFactory_(handlerFactory) {}

	::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

protected:
	::boost::shared_ptr< EngineServerIfFactory > handlerFactory_;
};

class EngineServerMultiface : virtual public EngineServerIf
{
public:
	EngineServerMultiface(std::vector<boost::shared_ptr<EngineServerIf> >& ifaces) : ifaces_(ifaces)
	{
	}
	virtual ~EngineServerMultiface() {}
protected:
	std::vector<boost::shared_ptr<EngineServerIf> > ifaces_;
	EngineServerMultiface() {}
	void add(boost::shared_ptr<EngineServerIf> iface)
	{
		ifaces_.push_back(iface);
	}
public:
	void start()
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->start();
		}
		ifaces_[i]->start();
	}

	void stop()
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->stop();
		}
		ifaces_[i]->stop();
	}

	bool addPlayer(const std::string& login, const std::string& password)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->addPlayer(login, password);
		}
		return ifaces_[i]->addPlayer(login, password);
	}

	void getPlayerFleets(FleetList& _return, const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlayerFleets(_return, pid, beginIndex, endIndex, sortType, asc);
		}
		ifaces_[i]->getPlayerFleets(_return, pid, beginIndex, endIndex, sortType, asc);
		return;
	}

	void getPlayerPlanets(PlanetList& _return, const Player_ID pid, const int32_t beginIndex, const int32_t endIndex, const Sort_Type::type sortType, const bool asc)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlayerPlanets(_return, pid, beginIndex, endIndex, sortType, asc);
		}
		ifaces_[i]->getPlayerPlanets(_return, pid, beginIndex, endIndex, sortType, asc);
		return;
	}

	void setPlayerFleetCode(const Player_ID pid, const std::string& code)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->setPlayerFleetCode(pid, code);
		}
		ifaces_[i]->setPlayerFleetCode(pid, code);
	}

	void setPlayerPlanetCode(const Player_ID pid, const std::string& code)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->setPlayerPlanetCode(pid, code);
		}
		ifaces_[i]->setPlayerPlanetCode(pid, code);
	}

	void setPlayerFleetBlocklyCode(const Player_ID pid, const std::string& code)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->setPlayerFleetBlocklyCode(pid, code);
		}
		ifaces_[i]->setPlayerFleetBlocklyCode(pid, code);
	}

	void setPlayerPlanetBlocklyCode(const Player_ID pid, const std::string& code)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->setPlayerPlanetBlocklyCode(pid, code);
		}
		ifaces_[i]->setPlayerPlanetBlocklyCode(pid, code);
	}

	void getPlayerFleetCode(CodeData& _return, const Player_ID pid)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlayerFleetCode(_return, pid);
		}
		ifaces_[i]->getPlayerFleetCode(_return, pid);
		return;
	}

	void getPlayerPlanetCode(CodeData& _return, const Player_ID pid)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlayerPlanetCode(_return, pid);
		}
		ifaces_[i]->getPlayerPlanetCode(_return, pid);
		return;
	}

	void getPlayers(std::vector<Player>& _return)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlayers(_return);
		}
		ifaces_[i]->getPlayers(_return);
		return;
	}

	void getPlayer(Player& _return, const Player_ID pid)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlayer(_return, pid);
		}
		ifaces_[i]->getPlayer(_return, pid);
		return;
	}

	void getPlanet(std::vector<Planet>& _return, const Coord& coord)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getPlanet(_return, coord);
		}
		ifaces_[i]->getPlanet(_return, coord);
		return;
	}

	void getFleet(Fleet& _return, const Fleet_ID fid)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getFleet(_return, fid);
		}
		ifaces_[i]->getFleet(_return, fid);
		return;
	}

	void logPlayer(OptionalPlayer& _return, const std::string& login, const std::string& password)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->logPlayer(_return, login, password);
		}
		ifaces_[i]->logPlayer(_return, login, password);
		return;
	}

	void incrementTutoDisplayed(const Player_ID pid, const std::string& tutoName)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->incrementTutoDisplayed(pid, tutoName);
		}
		ifaces_[i]->incrementTutoDisplayed(pid, tutoName);
	}

	void getFightReport(FightReport& _return, const int32_t id)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getFightReport(_return, id);
		}
		ifaces_[i]->getFightReport(_return, id);
		return;
	}

	void getTimeInfo(TimeInfo& _return)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getTimeInfo(_return);
		}
		ifaces_[i]->getTimeInfo(_return);
		return;
	}

	bool eraseAccount(const int32_t pid, const std::string& password)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->eraseAccount(pid, password);
		}
		return ifaces_[i]->eraseAccount(pid, password);
	}

	void getBuildingsInfo(std::vector<Building>& _return)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getBuildingsInfo(_return);
		}
		ifaces_[i]->getBuildingsInfo(_return);
		return;
	}

	void getCannonsInfo(std::vector<Cannon>& _return)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getCannonsInfo(_return);
		}
		ifaces_[i]->getCannonsInfo(_return);
		return;
	}

	void getShipsInfo(std::vector<Ship>& _return)
	{
		size_t sz = ifaces_.size();
		size_t i = 0;
		for(; i < (sz - 1); ++i)
		{
			ifaces_[i]->getShipsInfo(_return);
		}
		ifaces_[i]->getShipsInfo(_return);
		return;
	}

};

} // namespace

#endif
