/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thrift_types.h"

#include <algorithm>

namespace ndw
{

int _kEvent_TypeValues[] =
{
	Event_Type::FleetCodeError,
	Event_Type::FleetCodeExecError,
	Event_Type::PlanetCodeError,
	Event_Type::PlanetCodeExecError,
	Event_Type::Upgraded,
	Event_Type::ShipMade,
	Event_Type::PlanetHarvested,
	Event_Type::FleetWin,
	Event_Type::FleetDraw,
	Event_Type::FleetsGather,
	Event_Type::PlanetColonized,
	Event_Type::FleetLose,
	Event_Type::FleetDrop,
	Event_Type::PlanetLose,
	Event_Type::PlanetWin,
	Event_Type::CannonMade,
	Event_Type::Count
};
const char* _kEvent_TypeNames[] =
{
	"FleetCodeError",
	"FleetCodeExecError",
	"PlanetCodeError",
	"PlanetCodeExecError",
	"Upgraded",
	"ShipMade",
	"PlanetHarvested",
	"FleetWin",
	"FleetDraw",
	"FleetsGather",
	"PlanetColonized",
	"FleetLose",
	"FleetDrop",
	"PlanetLose",
	"PlanetWin",
	"CannonMade",
	"Count"
};
const std::map<int, const char*> _Event_Type_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(17, _kEvent_TypeValues, _kEvent_TypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kRessourceValues[] =
{
	Ressource::Metal,
	Ressource::Carbon,
	Ressource::Loicium,
	Ressource::Count
};
const char* _kRessourceNames[] =
{
	"Metal",
	"Carbon",
	"Loicium",
	"Count"
};
const std::map<int, const char*> _Ressource_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kRessourceValues, _kRessourceNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kPlanetTask_EnumValues[] =
{
	PlanetTask_Enum::UpgradeBuilding,
	PlanetTask_Enum::MakeShip,
	PlanetTask_Enum::MakeCannon,
	PlanetTask_Enum::Count
};
const char* _kPlanetTask_EnumNames[] =
{
	"UpgradeBuilding",
	"MakeShip",
	"MakeCannon",
	"Count"
};
const std::map<int, const char*> _PlanetTask_Enum_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kPlanetTask_EnumValues, _kPlanetTask_EnumNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kBuilding_EnumValues[] =
{
	Building_Enum::CommandCenter,
	Building_Enum::MetalMine,
	Building_Enum::CarbonMine,
	Building_Enum::LoiciumFilter,
	Building_Enum::Factory,
	Building_Enum::Laboratory,
	Building_Enum::CarbonicCentral,
	Building_Enum::SolarCentral,
	Building_Enum::GeothermicCentral,
	Building_Enum::Count
};
const char* _kBuilding_EnumNames[] =
{
	"CommandCenter",
	"MetalMine",
	"CarbonMine",
	"LoiciumFilter",
	"Factory",
	"Laboratory",
	"CarbonicCentral",
	"SolarCentral",
	"GeothermicCentral",
	"Count"
};
const std::map<int, const char*> _Building_Enum_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(10, _kBuilding_EnumValues, _kBuilding_EnumNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kShip_EnumValues[] =
{
	Ship_Enum::Mosquito,
	Ship_Enum::Hornet,
	Ship_Enum::Vulture,
	Ship_Enum::Dragon,
	Ship_Enum::Behemoth,
	Ship_Enum::Azathoth,
	Ship_Enum::Queen,
	Ship_Enum::Cargo,
	Ship_Enum::LargeCargo,
	Ship_Enum::Count
};
const char* _kShip_EnumNames[] =
{
	"Mosquito",
	"Hornet",
	"Vulture",
	"Dragon",
	"Behemoth",
	"Azathoth",
	"Queen",
	"Cargo",
	"LargeCargo",
	"Count"
};
const std::map<int, const char*> _Ship_Enum_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(10, _kShip_EnumValues, _kShip_EnumNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kCannon_EnumValues[] =
{
	Cannon_Enum::Cannon1,
	Cannon_Enum::Cannon2,
	Cannon_Enum::Cannon3,
	Cannon_Enum::Cannon4,
	Cannon_Enum::Cannon5,
	Cannon_Enum::Cannon6,
	Cannon_Enum::Count
};
const char* _kCannon_EnumNames[] =
{
	"Cannon1",
	"Cannon2",
	"Cannon3",
	"Cannon4",
	"Cannon5",
	"Cannon6",
	"Count"
};
const std::map<int, const char*> _Cannon_Enum_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(7, _kCannon_EnumValues, _kCannon_EnumNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kFleetTask_EnumValues[] =
{
	FleetTask_Enum::Move,
	FleetTask_Enum::Harvest,
	FleetTask_Enum::Colonize,
	FleetTask_Enum::Count
};
const char* _kFleetTask_EnumNames[] =
{
	"Move",
	"Harvest",
	"Colonize",
	"Count"
};
const std::map<int, const char*> _FleetTask_Enum_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kFleetTask_EnumValues, _kFleetTask_EnumNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kFleetAction_TypeValues[] =
{
	FleetAction_Type::Nothing,
	FleetAction_Type::Move,
	FleetAction_Type::Harvest,
	FleetAction_Type::Colonize
};
const char* _kFleetAction_TypeNames[] =
{
	"Nothing",
	"Move",
	"Harvest",
	"Colonize"
};
const std::map<int, const char*> _FleetAction_Type_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kFleetAction_TypeValues, _kFleetAction_TypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

int _kSort_TypeValues[] =
{
	Sort_Type::Name,
	Sort_Type::X,
	Sort_Type::Y,
	Sort_Type::Z,
	Sort_Type::M,
	Sort_Type::C,
	Sort_Type::L
};
const char* _kSort_TypeNames[] =
{
	"Name",
	"X",
	"Y",
	"Z",
	"M",
	"C",
	"L"
};
const std::map<int, const char*> _Sort_Type_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(7, _kSort_TypeValues, _kSort_TypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

const char* Coord::ascii_fingerprint = "6435B39C87AB0E30F30BEDEFD7328C0D";
const uint8_t Coord::binary_fingerprint[16] = {0x64, 0x35, 0xB3, 0x9C, 0x87, 0xAB, 0x0E, 0x30, 0xF3, 0x0B, 0xED, 0xEF, 0xD7, 0x32, 0x8C, 0x0D};

uint32_t Coord::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->X);
				this->__isset.X = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->Y);
				this->__isset.Y = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->Z);
				this->__isset.Z = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t Coord::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("Coord");

	xfer += oprot->writeFieldBegin("X", ::apache::thrift::protocol::T_I32, 1);
	xfer += oprot->writeI32(this->X);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("Y", ::apache::thrift::protocol::T_I32, 2);
	xfer += oprot->writeI32(this->Y);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("Z", ::apache::thrift::protocol::T_I32, 3);
	xfer += oprot->writeI32(this->Z);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(Coord& a, Coord& b)
{
	using ::std::swap;
	swap(a.X, b.X);
	swap(a.Y, b.Y);
	swap(a.Z, b.Z);
	swap(a.__isset, b.__isset);
}

const char* Event::ascii_fingerprint = "9C6D5D1EFAEA56027D176F213E40700B";
const uint8_t Event::binary_fingerprint[16] = {0x9C, 0x6D, 0x5D, 0x1E, 0xFA, 0xEA, 0x56, 0x02, 0x7D, 0x17, 0x6F, 0x21, 0x3E, 0x40, 0x70, 0x0B};

uint32_t Event::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->id);
				this->__isset.id = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->time);
				this->__isset.time = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				int32_t ecast0;
				xfer += iprot->readI32(ecast0);
				this->type = (Event_Type::type)ecast0;
				this->__isset.type = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->comment);
				this->__isset.comment = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 5:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->value);
				this->__isset.value = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 6:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->viewed);
				this->__isset.viewed = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t Event::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("Event");

	xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 1);
	xfer += oprot->writeI32(this->id);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("time", ::apache::thrift::protocol::T_I32, 2);
	xfer += oprot->writeI32(this->time);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 3);
	xfer += oprot->writeI32((int32_t)this->type);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("comment", ::apache::thrift::protocol::T_STRING, 4);
	xfer += oprot->writeString(this->comment);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_I32, 5);
	xfer += oprot->writeI32(this->value);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("viewed", ::apache::thrift::protocol::T_BOOL, 6);
	xfer += oprot->writeBool(this->viewed);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(Event& a, Event& b)
{
	using ::std::swap;
	swap(a.id, b.id);
	swap(a.time, b.time);
	swap(a.type, b.type);
	swap(a.comment, b.comment);
	swap(a.value, b.value);
	swap(a.viewed, b.viewed);
	swap(a.__isset, b.__isset);
}

const char* CodeData::ascii_fingerprint = "AC16F1200213405F9A9267FCBF95F39A";
const uint8_t CodeData::binary_fingerprint[16] = {0xAC, 0x16, 0xF1, 0x20, 0x02, 0x13, 0x40, 0x5F, 0x9A, 0x92, 0x67, 0xFC, 0xBF, 0x95, 0xF3, 0x9A};

uint32_t CodeData::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->blocklyCode);
				this->__isset.blocklyCode = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->code);
				this->__isset.code = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->failCount);
				this->__isset.failCount = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->lastError);
				this->__isset.lastError = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t CodeData::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("CodeData");

	xfer += oprot->writeFieldBegin("blocklyCode", ::apache::thrift::protocol::T_STRING, 1);
	xfer += oprot->writeString(this->blocklyCode);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("code", ::apache::thrift::protocol::T_STRING, 2);
	xfer += oprot->writeString(this->code);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("failCount", ::apache::thrift::protocol::T_I32, 3);
	xfer += oprot->writeI32(this->failCount);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("lastError", ::apache::thrift::protocol::T_STRING, 4);
	xfer += oprot->writeString(this->lastError);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(CodeData& a, CodeData& b)
{
	using ::std::swap;
	swap(a.blocklyCode, b.blocklyCode);
	swap(a.code, b.code);
	swap(a.failCount, b.failCount);
	swap(a.lastError, b.lastError);
	swap(a.__isset, b.__isset);
}

const char* Player::ascii_fingerprint = "831CB4584F9FEEEF24515F3E3C644BDF";
const uint8_t Player::binary_fingerprint[16] = {0x83, 0x1C, 0xB4, 0x58, 0x4F, 0x9F, 0xEE, 0xEF, 0x24, 0x51, 0x5F, 0x3E, 0x3C, 0x64, 0x4B, 0xDF};

uint32_t Player::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->id);
				this->__isset.id = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->login);
				this->__isset.login = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->password);
				this->__isset.password = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->fleetsCode.read(iprot);
				this->__isset.fleetsCode = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 5:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->planetsCode.read(iprot);
				this->__isset.planetsCode = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 6:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->eventList.clear();
					uint32_t _size1;
					::apache::thrift::protocol::TType _etype4;
					xfer += iprot->readListBegin(_etype4, _size1);
					this->eventList.resize(_size1);
					uint32_t _i5;
					for(_i5 = 0; _i5 < _size1; ++_i5)
					{
						xfer += this->eventList[_i5].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.eventList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 7:
			if(ftype == ::apache::thrift::protocol::T_MAP)
			{
				{
					this->tutoDisplayed.clear();
					uint32_t _size6;
					::apache::thrift::protocol::TType _ktype7;
					::apache::thrift::protocol::TType _vtype8;
					xfer += iprot->readMapBegin(_ktype7, _vtype8, _size6);
					uint32_t _i10;
					for(_i10 = 0; _i10 < _size6; ++_i10)
					{
						std::string _key11;
						xfer += iprot->readString(_key11);
						int32_t& _val12 = this->tutoDisplayed[_key11];
						xfer += iprot->readI32(_val12);
					}
					xfer += iprot->readMapEnd();
				}
				this->__isset.tutoDisplayed = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 8:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->mainPlanet.read(iprot);
				this->__isset.mainPlanet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 9:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->score);
				this->__isset.score = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t Player::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("Player");

	xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 1);
	xfer += oprot->writeI32(this->id);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("login", ::apache::thrift::protocol::T_STRING, 2);
	xfer += oprot->writeString(this->login);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("password", ::apache::thrift::protocol::T_STRING, 3);
	xfer += oprot->writeString(this->password);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("fleetsCode", ::apache::thrift::protocol::T_STRUCT, 4);
	xfer += this->fleetsCode.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("planetsCode", ::apache::thrift::protocol::T_STRUCT, 5);
	xfer += this->planetsCode.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("eventList", ::apache::thrift::protocol::T_LIST, 6);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->eventList.size()));
		std::vector<Event> ::const_iterator _iter13;
		for(_iter13 = this->eventList.begin(); _iter13 != this->eventList.end(); ++_iter13)
		{
			xfer += (*_iter13).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("tutoDisplayed", ::apache::thrift::protocol::T_MAP, 7);
	{
		xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->tutoDisplayed.size()));
		std::map<std::string, int32_t> ::const_iterator _iter14;
		for(_iter14 = this->tutoDisplayed.begin(); _iter14 != this->tutoDisplayed.end(); ++_iter14)
		{
			xfer += oprot->writeString(_iter14->first);
			xfer += oprot->writeI32(_iter14->second);
		}
		xfer += oprot->writeMapEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("mainPlanet", ::apache::thrift::protocol::T_STRUCT, 8);
	xfer += this->mainPlanet.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("score", ::apache::thrift::protocol::T_I32, 9);
	xfer += oprot->writeI32(this->score);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(Player& a, Player& b)
{
	using ::std::swap;
	swap(a.id, b.id);
	swap(a.login, b.login);
	swap(a.password, b.password);
	swap(a.fleetsCode, b.fleetsCode);
	swap(a.planetsCode, b.planetsCode);
	swap(a.eventList, b.eventList);
	swap(a.tutoDisplayed, b.tutoDisplayed);
	swap(a.mainPlanet, b.mainPlanet);
	swap(a.score, b.score);
	swap(a.__isset, b.__isset);
}

const char* RessourceSet::ascii_fingerprint = "A803C54EAD95E24D90C5E66FB98EA72B";
const uint8_t RessourceSet::binary_fingerprint[16] = {0xA8, 0x03, 0xC5, 0x4E, 0xAD, 0x95, 0xE2, 0x4D, 0x90, 0xC5, 0xE6, 0x6F, 0xB9, 0x8E, 0xA7, 0x2B};

uint32_t RessourceSet::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->tab.clear();
					uint32_t _size15;
					::apache::thrift::protocol::TType _etype18;
					xfer += iprot->readListBegin(_etype18, _size15);
					this->tab.resize(_size15);
					uint32_t _i19;
					for(_i19 = 0; _i19 < _size15; ++_i19)
					{
						xfer += iprot->readI32(this->tab[_i19]);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.tab = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t RessourceSet::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("RessourceSet");

	xfer += oprot->writeFieldBegin("tab", ::apache::thrift::protocol::T_LIST, 1);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->tab.size()));
		std::vector<int32_t> ::const_iterator _iter20;
		for(_iter20 = this->tab.begin(); _iter20 != this->tab.end(); ++_iter20)
		{
			xfer += oprot->writeI32((*_iter20));
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(RessourceSet& a, RessourceSet& b)
{
	using ::std::swap;
	swap(a.tab, b.tab);
	swap(a.__isset, b.__isset);
}

const char* PlanetTask::ascii_fingerprint = "19D77FE5BA23B2E932882446FD75CA83";
const uint8_t PlanetTask::binary_fingerprint[16] = {0x19, 0xD7, 0x7F, 0xE5, 0xBA, 0x23, 0xB2, 0xE9, 0x32, 0x88, 0x24, 0x46, 0xFD, 0x75, 0xCA, 0x83};

uint32_t PlanetTask::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				int32_t ecast21;
				xfer += iprot->readI32(ecast21);
				this->type = (PlanetTask_Enum::type)ecast21;
				this->__isset.type = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->value);
				this->__isset.value = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->value2);
				this->__isset.value2 = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->lauchTime);
				this->__isset.lauchTime = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 5:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->duration);
				this->__isset.duration = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 6:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->startCos.read(iprot);
				this->__isset.startCos = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 7:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->expired);
				this->__isset.expired = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t PlanetTask::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("PlanetTask");

	xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 1);
	xfer += oprot->writeI32((int32_t)this->type);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("value", ::apache::thrift::protocol::T_I32, 2);
	xfer += oprot->writeI32(this->value);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("value2", ::apache::thrift::protocol::T_I32, 3);
	xfer += oprot->writeI32(this->value2);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("lauchTime", ::apache::thrift::protocol::T_I32, 4);
	xfer += oprot->writeI32(this->lauchTime);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("duration", ::apache::thrift::protocol::T_I32, 5);
	xfer += oprot->writeI32(this->duration);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("startCos", ::apache::thrift::protocol::T_STRUCT, 6);
	xfer += this->startCos.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("expired", ::apache::thrift::protocol::T_BOOL, 7);
	xfer += oprot->writeBool(this->expired);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(PlanetTask& a, PlanetTask& b)
{
	using ::std::swap;
	swap(a.type, b.type);
	swap(a.value, b.value);
	swap(a.value2, b.value2);
	swap(a.lauchTime, b.lauchTime);
	swap(a.duration, b.duration);
	swap(a.startCos, b.startCos);
	swap(a.expired, b.expired);
	swap(a.__isset, b.__isset);
}

const char* FleetTask::ascii_fingerprint = "0A2DD41FFDA24B0F547E4AACEDE12092";
const uint8_t FleetTask::binary_fingerprint[16] = {0x0A, 0x2D, 0xD4, 0x1F, 0xFD, 0xA2, 0x4B, 0x0F, 0x54, 0x7E, 0x4A, 0xAC, 0xED, 0xE1, 0x20, 0x92};

uint32_t FleetTask::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				int32_t ecast22;
				xfer += iprot->readI32(ecast22);
				this->type = (FleetTask_Enum::type)ecast22;
				this->__isset.type = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->lauchTime);
				this->__isset.lauchTime = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->duration);
				this->__isset.duration = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->position.read(iprot);
				this->__isset.position = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 5:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->expired);
				this->__isset.expired = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t FleetTask::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("FleetTask");

	xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_I32, 1);
	xfer += oprot->writeI32((int32_t)this->type);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("lauchTime", ::apache::thrift::protocol::T_I32, 2);
	xfer += oprot->writeI32(this->lauchTime);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("duration", ::apache::thrift::protocol::T_I32, 3);
	xfer += oprot->writeI32(this->duration);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("position", ::apache::thrift::protocol::T_STRUCT, 4);
	xfer += this->position.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("expired", ::apache::thrift::protocol::T_BOOL, 5);
	xfer += oprot->writeBool(this->expired);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(FleetTask& a, FleetTask& b)
{
	using ::std::swap;
	swap(a.type, b.type);
	swap(a.lauchTime, b.lauchTime);
	swap(a.duration, b.duration);
	swap(a.position, b.position);
	swap(a.expired, b.expired);
	swap(a.__isset, b.__isset);
}

const char* Planet::ascii_fingerprint = "E178018DDB3E0BA0A52EE04DCCAB8F93";
const uint8_t Planet::binary_fingerprint[16] = {0xE1, 0x78, 0x01, 0x8D, 0xDB, 0x3E, 0x0B, 0xA0, 0xA5, 0x2E, 0xE0, 0x4D, 0xCC, 0xAB, 0x8F, 0x93};

uint32_t Planet::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->name);
				this->__isset.name = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->coord.read(iprot);
				this->__isset.coord = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->playerId);
				this->__isset.playerId = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->buildingList.clear();
					uint32_t _size23;
					::apache::thrift::protocol::TType _etype26;
					xfer += iprot->readListBegin(_etype26, _size23);
					this->buildingList.resize(_size23);
					uint32_t _i27;
					for(_i27 = 0; _i27 < _size23; ++_i27)
					{
						xfer += iprot->readI32(this->buildingList[_i27]);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.buildingList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 5:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->taskQueue.clear();
					uint32_t _size28;
					::apache::thrift::protocol::TType _etype31;
					xfer += iprot->readListBegin(_etype31, _size28);
					this->taskQueue.resize(_size28);
					uint32_t _i32;
					for(_i32 = 0; _i32 < _size28; ++_i32)
					{
						xfer += this->taskQueue[_i32].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.taskQueue = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 6:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->ressourceSet.read(iprot);
				this->__isset.ressourceSet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 7:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->eventList.clear();
					uint32_t _size33;
					::apache::thrift::protocol::TType _etype36;
					xfer += iprot->readListBegin(_etype36, _size33);
					this->eventList.resize(_size33);
					uint32_t _i37;
					for(_i37 = 0; _i37 < _size33; ++_i37)
					{
						xfer += this->eventList[_i37].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.eventList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 8:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->cannonTab.clear();
					uint32_t _size38;
					::apache::thrift::protocol::TType _etype41;
					xfer += iprot->readListBegin(_etype41, _size38);
					this->cannonTab.resize(_size38);
					uint32_t _i42;
					for(_i42 = 0; _i42 < _size38; ++_i42)
					{
						xfer += iprot->readI32(this->cannonTab[_i42]);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.cannonTab = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t Planet::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("Planet");

	xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
	xfer += oprot->writeString(this->name);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("coord", ::apache::thrift::protocol::T_STRUCT, 2);
	xfer += this->coord.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("playerId", ::apache::thrift::protocol::T_I32, 3);
	xfer += oprot->writeI32(this->playerId);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("buildingList", ::apache::thrift::protocol::T_LIST, 4);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->buildingList.size()));
		std::vector<int32_t> ::const_iterator _iter43;
		for(_iter43 = this->buildingList.begin(); _iter43 != this->buildingList.end(); ++_iter43)
		{
			xfer += oprot->writeI32((*_iter43));
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("taskQueue", ::apache::thrift::protocol::T_LIST, 5);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->taskQueue.size()));
		std::vector<PlanetTask> ::const_iterator _iter44;
		for(_iter44 = this->taskQueue.begin(); _iter44 != this->taskQueue.end(); ++_iter44)
		{
			xfer += (*_iter44).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("ressourceSet", ::apache::thrift::protocol::T_STRUCT, 6);
	xfer += this->ressourceSet.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("eventList", ::apache::thrift::protocol::T_LIST, 7);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->eventList.size()));
		std::vector<Event> ::const_iterator _iter45;
		for(_iter45 = this->eventList.begin(); _iter45 != this->eventList.end(); ++_iter45)
		{
			xfer += (*_iter45).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("cannonTab", ::apache::thrift::protocol::T_LIST, 8);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->cannonTab.size()));
		std::vector<int32_t> ::const_iterator _iter46;
		for(_iter46 = this->cannonTab.begin(); _iter46 != this->cannonTab.end(); ++_iter46)
		{
			xfer += oprot->writeI32((*_iter46));
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(Planet& a, Planet& b)
{
	using ::std::swap;
	swap(a.name, b.name);
	swap(a.coord, b.coord);
	swap(a.playerId, b.playerId);
	swap(a.buildingList, b.buildingList);
	swap(a.taskQueue, b.taskQueue);
	swap(a.ressourceSet, b.ressourceSet);
	swap(a.eventList, b.eventList);
	swap(a.cannonTab, b.cannonTab);
	swap(a.__isset, b.__isset);
}

const char* Fleet::ascii_fingerprint = "7F2E377571D9724BAAE2721C92DC886A";
const uint8_t Fleet::binary_fingerprint[16] = {0x7F, 0x2E, 0x37, 0x75, 0x71, 0xD9, 0x72, 0x4B, 0xAA, 0xE2, 0x72, 0x1C, 0x92, 0xDC, 0x88, 0x6A};

uint32_t Fleet::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->id);
				this->__isset.id = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->playerId);
				this->__isset.playerId = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 30:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->coord.read(iprot);
				this->__isset.coord = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 40:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->origin.read(iprot);
				this->__isset.origin = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 50:
			if(ftype == ::apache::thrift::protocol::T_STRING)
			{
				xfer += iprot->readString(this->name);
				this->__isset.name = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 60:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->shipList.clear();
					uint32_t _size47;
					::apache::thrift::protocol::TType _etype50;
					xfer += iprot->readListBegin(_etype50, _size47);
					this->shipList.resize(_size47);
					uint32_t _i51;
					for(_i51 = 0; _i51 < _size47; ++_i51)
					{
						xfer += iprot->readI32(this->shipList[_i51]);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.shipList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 70:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->ressourceSet.read(iprot);
				this->__isset.ressourceSet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 80:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->taskQueue.clear();
					uint32_t _size52;
					::apache::thrift::protocol::TType _etype55;
					xfer += iprot->readListBegin(_etype55, _size52);
					this->taskQueue.resize(_size52);
					uint32_t _i56;
					for(_i56 = 0; _i56 < _size52; ++_i56)
					{
						xfer += this->taskQueue[_i56].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.taskQueue = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 90:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->eventList.clear();
					uint32_t _size57;
					::apache::thrift::protocol::TType _etype60;
					xfer += iprot->readListBegin(_etype60, _size57);
					this->eventList.resize(_size57);
					uint32_t _i61;
					for(_i61 = 0; _i61 < _size57; ++_i61)
					{
						xfer += this->eventList[_i61].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.eventList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t Fleet::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("Fleet");

	xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 10);
	xfer += oprot->writeI32(this->id);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("playerId", ::apache::thrift::protocol::T_I32, 20);
	xfer += oprot->writeI32(this->playerId);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("coord", ::apache::thrift::protocol::T_STRUCT, 30);
	xfer += this->coord.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("origin", ::apache::thrift::protocol::T_STRUCT, 40);
	xfer += this->origin.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 50);
	xfer += oprot->writeString(this->name);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("shipList", ::apache::thrift::protocol::T_LIST, 60);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->shipList.size()));
		std::vector<int32_t> ::const_iterator _iter62;
		for(_iter62 = this->shipList.begin(); _iter62 != this->shipList.end(); ++_iter62)
		{
			xfer += oprot->writeI32((*_iter62));
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("ressourceSet", ::apache::thrift::protocol::T_STRUCT, 70);
	xfer += this->ressourceSet.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("taskQueue", ::apache::thrift::protocol::T_LIST, 80);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->taskQueue.size()));
		std::vector<FleetTask> ::const_iterator _iter63;
		for(_iter63 = this->taskQueue.begin(); _iter63 != this->taskQueue.end(); ++_iter63)
		{
			xfer += (*_iter63).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("eventList", ::apache::thrift::protocol::T_LIST, 90);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->eventList.size()));
		std::vector<Event> ::const_iterator _iter64;
		for(_iter64 = this->eventList.begin(); _iter64 != this->eventList.end(); ++_iter64)
		{
			xfer += (*_iter64).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(Fleet& a, Fleet& b)
{
	using ::std::swap;
	swap(a.id, b.id);
	swap(a.playerId, b.playerId);
	swap(a.coord, b.coord);
	swap(a.origin, b.origin);
	swap(a.name, b.name);
	swap(a.shipList, b.shipList);
	swap(a.ressourceSet, b.ressourceSet);
	swap(a.taskQueue, b.taskQueue);
	swap(a.eventList, b.eventList);
	swap(a.__isset, b.__isset);
}

const char* FleetAction::ascii_fingerprint = "096C62D67189AD8DEE6942D975E45799";
const uint8_t FleetAction::binary_fingerprint[16] = {0x09, 0x6C, 0x62, 0xD6, 0x71, 0x89, 0xAD, 0x8D, 0xEE, 0x69, 0x42, 0xD9, 0x75, 0xE4, 0x57, 0x99};

uint32_t FleetAction::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				int32_t ecast65;
				xfer += iprot->readI32(ecast65);
				this->action = (FleetAction_Type::type)ecast65;
				this->__isset.action = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->target.read(iprot);
				this->__isset.target = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t FleetAction::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("FleetAction");

	xfer += oprot->writeFieldBegin("action", ::apache::thrift::protocol::T_I32, 1);
	xfer += oprot->writeI32((int32_t)this->action);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("target", ::apache::thrift::protocol::T_STRUCT, 2);
	xfer += this->target.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(FleetAction& a, FleetAction& b)
{
	using ::std::swap;
	swap(a.action, b.action);
	swap(a.target, b.target);
	swap(a.__isset, b.__isset);
}

const char* FleetFightInfo::ascii_fingerprint = "C87F4D7054D96EC55B454D5172A46D0D";
const uint8_t FleetFightInfo::binary_fingerprint[16] = {0xC8, 0x7F, 0x4D, 0x70, 0x54, 0xD9, 0x6E, 0xC5, 0x5B, 0x45, 0x4D, 0x51, 0x72, 0xA4, 0x6D, 0x0D};

uint32_t FleetFightInfo::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->before.read(iprot);
				this->__isset.before = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->after.read(iprot);
				this->__isset.after = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t FleetFightInfo::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("FleetFightInfo");

	xfer += oprot->writeFieldBegin("before", ::apache::thrift::protocol::T_STRUCT, 10);
	xfer += this->before.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("after", ::apache::thrift::protocol::T_STRUCT, 20);
	xfer += this->after.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(FleetFightInfo& a, FleetFightInfo& b)
{
	using ::std::swap;
	swap(a.before, b.before);
	swap(a.after, b.after);
	swap(a.__isset, b.__isset);
}

const char* FleetReport::ascii_fingerprint = "1F5F50236CAA73FEC7CFE595305D8FB4";
const uint8_t FleetReport::binary_fingerprint[16] = {0x1F, 0x5F, 0x50, 0x23, 0x6C, 0xAA, 0x73, 0xFE, 0xC7, 0xCF, 0xE5, 0x95, 0x30, 0x5D, 0x8F, 0xB4};

uint32_t FleetReport::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->isDead);
				this->__isset.isDead = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->hasFight);
				this->__isset.hasFight = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 30:
			if(ftype == ::apache::thrift::protocol::T_SET)
			{
				{
					this->enemySet.clear();
					uint32_t _size66;
					::apache::thrift::protocol::TType _etype69;
					xfer += iprot->readSetBegin(_etype69, _size66);
					uint32_t _i70;
					for(_i70 = 0; _i70 < _size66; ++_i70)
					{
						int32_t _elem71;
						xfer += iprot->readI32(_elem71);
						this->enemySet.insert(_elem71);
					}
					xfer += iprot->readSetEnd();
				}
				this->__isset.enemySet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 40:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->fightInfo.read(iprot);
				this->__isset.fightInfo = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t FleetReport::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("FleetReport");

	xfer += oprot->writeFieldBegin("isDead", ::apache::thrift::protocol::T_BOOL, 10);
	xfer += oprot->writeBool(this->isDead);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("hasFight", ::apache::thrift::protocol::T_BOOL, 20);
	xfer += oprot->writeBool(this->hasFight);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("enemySet", ::apache::thrift::protocol::T_SET, 30);
	{
		xfer += oprot->writeSetBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->enemySet.size()));
		std::set<int32_t> ::const_iterator _iter72;
		for(_iter72 = this->enemySet.begin(); _iter72 != this->enemySet.end(); ++_iter72)
		{
			xfer += oprot->writeI32((*_iter72));
		}
		xfer += oprot->writeSetEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("fightInfo", ::apache::thrift::protocol::T_STRUCT, 40);
	xfer += this->fightInfo.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(FleetReport& a, FleetReport& b)
{
	using ::std::swap;
	swap(a.isDead, b.isDead);
	swap(a.hasFight, b.hasFight);
	swap(a.enemySet, b.enemySet);
	swap(a.fightInfo, b.fightInfo);
	swap(a.__isset, b.__isset);
}

const char* PlanetFightInfo::ascii_fingerprint = "58D0452C00146C814E77E7A0E59D7B69";
const uint8_t PlanetFightInfo::binary_fingerprint[16] = {0x58, 0xD0, 0x45, 0x2C, 0x00, 0x14, 0x6C, 0x81, 0x4E, 0x77, 0xE7, 0xA0, 0xE5, 0x9D, 0x7B, 0x69};

uint32_t PlanetFightInfo::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->before.read(iprot);
				this->__isset.before = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->after.read(iprot);
				this->__isset.after = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t PlanetFightInfo::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("PlanetFightInfo");

	xfer += oprot->writeFieldBegin("before", ::apache::thrift::protocol::T_STRUCT, 10);
	xfer += this->before.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("after", ::apache::thrift::protocol::T_STRUCT, 20);
	xfer += this->after.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(PlanetFightInfo& a, PlanetFightInfo& b)
{
	using ::std::swap;
	swap(a.before, b.before);
	swap(a.after, b.after);
	swap(a.__isset, b.__isset);
}

const char* PlanetReport::ascii_fingerprint = "5A447E0DC2E3D0415B74B5511AE0EB98";
const uint8_t PlanetReport::binary_fingerprint[16] = {0x5A, 0x44, 0x7E, 0x0D, 0xC2, 0xE3, 0xD0, 0x41, 0x5B, 0x74, 0xB5, 0x51, 0x1A, 0xE0, 0xEB, 0x98};

uint32_t PlanetReport::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->isDead);
				this->__isset.isDead = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->hasFight);
				this->__isset.hasFight = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 30:
			if(ftype == ::apache::thrift::protocol::T_SET)
			{
				{
					this->enemySet.clear();
					uint32_t _size73;
					::apache::thrift::protocol::TType _etype76;
					xfer += iprot->readSetBegin(_etype76, _size73);
					uint32_t _i77;
					for(_i77 = 0; _i77 < _size73; ++_i77)
					{
						int32_t _elem78;
						xfer += iprot->readI32(_elem78);
						this->enemySet.insert(_elem78);
					}
					xfer += iprot->readSetEnd();
				}
				this->__isset.enemySet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 40:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->fightInfo.read(iprot);
				this->__isset.fightInfo = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t PlanetReport::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("PlanetReport");

	xfer += oprot->writeFieldBegin("isDead", ::apache::thrift::protocol::T_BOOL, 10);
	xfer += oprot->writeBool(this->isDead);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("hasFight", ::apache::thrift::protocol::T_BOOL, 20);
	xfer += oprot->writeBool(this->hasFight);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("enemySet", ::apache::thrift::protocol::T_SET, 30);
	{
		xfer += oprot->writeSetBegin(::apache::thrift::protocol::T_I32, static_cast<uint32_t>(this->enemySet.size()));
		std::set<int32_t> ::const_iterator _iter79;
		for(_iter79 = this->enemySet.begin(); _iter79 != this->enemySet.end(); ++_iter79)
		{
			xfer += oprot->writeI32((*_iter79));
		}
		xfer += oprot->writeSetEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("fightInfo", ::apache::thrift::protocol::T_STRUCT, 40);
	xfer += this->fightInfo.write(oprot);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(PlanetReport& a, PlanetReport& b)
{
	using ::std::swap;
	swap(a.isDead, b.isDead);
	swap(a.hasFight, b.hasFight);
	swap(a.enemySet, b.enemySet);
	swap(a.fightInfo, b.fightInfo);
	swap(a.__isset, b.__isset);
}

const char* FightReport::ascii_fingerprint = "96A98A1FF609CB59E84D83BDF94663D3";
const uint8_t FightReport::binary_fingerprint[16] = {0x96, 0xA9, 0x8A, 0x1F, 0xF6, 0x09, 0xCB, 0x59, 0xE8, 0x4D, 0x83, 0xBD, 0xF9, 0x46, 0x63, 0xD3};

uint32_t FightReport::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->fleetList.clear();
					uint32_t _size80;
					::apache::thrift::protocol::TType _etype83;
					xfer += iprot->readListBegin(_etype83, _size80);
					this->fleetList.resize(_size80);
					uint32_t _i84;
					for(_i84 = 0; _i84 < _size80; ++_i84)
					{
						xfer += this->fleetList[_i84].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.fleetList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_BOOL)
			{
				xfer += iprot->readBool(this->hasPlanet);
				this->__isset.hasPlanet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 30:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->planet.read(iprot);
				this->__isset.planet = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t FightReport::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("FightReport");

	xfer += oprot->writeFieldBegin("fleetList", ::apache::thrift::protocol::T_LIST, 10);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->fleetList.size()));
		std::vector<FleetReport> ::const_iterator _iter85;
		for(_iter85 = this->fleetList.begin(); _iter85 != this->fleetList.end(); ++_iter85)
		{
			xfer += (*_iter85).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("hasPlanet", ::apache::thrift::protocol::T_BOOL, 20);
	xfer += oprot->writeBool(this->hasPlanet);
	xfer += oprot->writeFieldEnd();

	if(this->__isset.planet)
	{
		xfer += oprot->writeFieldBegin("planet", ::apache::thrift::protocol::T_STRUCT, 30);
		xfer += this->planet.write(oprot);
		xfer += oprot->writeFieldEnd();
	}
	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(FightReport& a, FightReport& b)
{
	using ::std::swap;
	swap(a.fleetList, b.fleetList);
	swap(a.hasPlanet, b.hasPlanet);
	swap(a.planet, b.planet);
	swap(a.__isset, b.__isset);
}

const char* Universe::ascii_fingerprint = "923D2BD6A38F7ED98D913B8CB37A26C5";
const uint8_t Universe::binary_fingerprint[16] = {0x92, 0x3D, 0x2B, 0xD6, 0xA3, 0x8F, 0x7E, 0xD9, 0x8D, 0x91, 0x3B, 0x8C, 0xB3, 0x7A, 0x26, 0xC5};

uint32_t Universe::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_MAP)
			{
				{
					this->playerMap.clear();
					uint32_t _size86;
					::apache::thrift::protocol::TType _ktype87;
					::apache::thrift::protocol::TType _vtype88;
					xfer += iprot->readMapBegin(_ktype87, _vtype88, _size86);
					uint32_t _i90;
					for(_i90 = 0; _i90 < _size86; ++_i90)
					{
						Player_ID _key91;
						xfer += iprot->readI32(_key91);
						Player& _val92 = this->playerMap[_key91];
						xfer += _val92.read(iprot);
					}
					xfer += iprot->readMapEnd();
				}
				this->__isset.playerMap = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 2:
			if(ftype == ::apache::thrift::protocol::T_MAP)
			{
				{
					this->planetMap.clear();
					uint32_t _size93;
					::apache::thrift::protocol::TType _ktype94;
					::apache::thrift::protocol::TType _vtype95;
					xfer += iprot->readMapBegin(_ktype94, _vtype95, _size93);
					uint32_t _i97;
					for(_i97 = 0; _i97 < _size93; ++_i97)
					{
						Coord _key98;
						xfer += _key98.read(iprot);
						Planet& _val99 = this->planetMap[_key98];
						xfer += _val99.read(iprot);
					}
					xfer += iprot->readMapEnd();
				}
				this->__isset.planetMap = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 3:
			if(ftype == ::apache::thrift::protocol::T_MAP)
			{
				{
					this->fleetMap.clear();
					uint32_t _size100;
					::apache::thrift::protocol::TType _ktype101;
					::apache::thrift::protocol::TType _vtype102;
					xfer += iprot->readMapBegin(_ktype101, _vtype102, _size100);
					uint32_t _i104;
					for(_i104 = 0; _i104 < _size100; ++_i104)
					{
						Fleet_ID _key105;
						xfer += iprot->readI32(_key105);
						Fleet& _val106 = this->fleetMap[_key105];
						xfer += _val106.read(iprot);
					}
					xfer += iprot->readMapEnd();
				}
				this->__isset.fleetMap = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 4:
			if(ftype == ::apache::thrift::protocol::T_MAP)
			{
				{
					this->reportMap.clear();
					uint32_t _size107;
					::apache::thrift::protocol::TType _ktype108;
					::apache::thrift::protocol::TType _vtype109;
					xfer += iprot->readMapBegin(_ktype108, _vtype109, _size107);
					uint32_t _i111;
					for(_i111 = 0; _i111 < _size107; ++_i111)
					{
						int32_t _key112;
						xfer += iprot->readI32(_key112);
						FightReport& _val113 = this->reportMap[_key112];
						xfer += _val113.read(iprot);
					}
					xfer += iprot->readMapEnd();
				}
				this->__isset.reportMap = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 5:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->nextPlayerID);
				this->__isset.nextPlayerID = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 6:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->nextFleetID);
				this->__isset.nextFleetID = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 7:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->time);
				this->__isset.time = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t Universe::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("Universe");

	xfer += oprot->writeFieldBegin("playerMap", ::apache::thrift::protocol::T_MAP, 1);
	{
		xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->playerMap.size()));
		std::map<Player_ID, Player> ::const_iterator _iter114;
		for(_iter114 = this->playerMap.begin(); _iter114 != this->playerMap.end(); ++_iter114)
		{
			xfer += oprot->writeI32(_iter114->first);
			xfer += _iter114->second.write(oprot);
		}
		xfer += oprot->writeMapEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("planetMap", ::apache::thrift::protocol::T_MAP, 2);
	{
		xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRUCT, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->planetMap.size()));
		std::map<Coord, Planet> ::const_iterator _iter115;
		for(_iter115 = this->planetMap.begin(); _iter115 != this->planetMap.end(); ++_iter115)
		{
			xfer += _iter115->first.write(oprot);
			xfer += _iter115->second.write(oprot);
		}
		xfer += oprot->writeMapEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("fleetMap", ::apache::thrift::protocol::T_MAP, 3);
	{
		xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->fleetMap.size()));
		std::map<Fleet_ID, Fleet> ::const_iterator _iter116;
		for(_iter116 = this->fleetMap.begin(); _iter116 != this->fleetMap.end(); ++_iter116)
		{
			xfer += oprot->writeI32(_iter116->first);
			xfer += _iter116->second.write(oprot);
		}
		xfer += oprot->writeMapEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("reportMap", ::apache::thrift::protocol::T_MAP, 4);
	{
		xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_I32, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->reportMap.size()));
		std::map<int32_t, FightReport> ::const_iterator _iter117;
		for(_iter117 = this->reportMap.begin(); _iter117 != this->reportMap.end(); ++_iter117)
		{
			xfer += oprot->writeI32(_iter117->first);
			xfer += _iter117->second.write(oprot);
		}
		xfer += oprot->writeMapEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("nextPlayerID", ::apache::thrift::protocol::T_I32, 5);
	xfer += oprot->writeI32(this->nextPlayerID);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("nextFleetID", ::apache::thrift::protocol::T_I32, 6);
	xfer += oprot->writeI32(this->nextFleetID);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("time", ::apache::thrift::protocol::T_I32, 7);
	xfer += oprot->writeI32(this->time);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(Universe& a, Universe& b)
{
	using ::std::swap;
	swap(a.playerMap, b.playerMap);
	swap(a.planetMap, b.planetMap);
	swap(a.fleetMap, b.fleetMap);
	swap(a.reportMap, b.reportMap);
	swap(a.nextPlayerID, b.nextPlayerID);
	swap(a.nextFleetID, b.nextFleetID);
	swap(a.time, b.time);
	swap(a.__isset, b.__isset);
}

const char* OptionalPlayer::ascii_fingerprint = "0C21250C1C875666C102C0D50CFCEE12";
const uint8_t OptionalPlayer::binary_fingerprint[16] = {0x0C, 0x21, 0x25, 0x0C, 0x1C, 0x87, 0x56, 0x66, 0xC1, 0x02, 0xC0, 0xD5, 0x0C, 0xFC, 0xEE, 0x12};

uint32_t OptionalPlayer::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 1:
			if(ftype == ::apache::thrift::protocol::T_STRUCT)
			{
				xfer += this->player.read(iprot);
				this->__isset.player = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t OptionalPlayer::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("OptionalPlayer");

	if(this->__isset.player)
	{
		xfer += oprot->writeFieldBegin("player", ::apache::thrift::protocol::T_STRUCT, 1);
		xfer += this->player.write(oprot);
		xfer += oprot->writeFieldEnd();
	}
	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(OptionalPlayer& a, OptionalPlayer& b)
{
	using ::std::swap;
	swap(a.player, b.player);
	swap(a.__isset, b.__isset);
}

const char* TimeInfo::ascii_fingerprint = "9EA78140CD5F29ED0DA93A6F86CC34E1";
const uint8_t TimeInfo::binary_fingerprint[16] = {0x9E, 0xA7, 0x81, 0x40, 0xCD, 0x5F, 0x29, 0xED, 0x0D, 0xA9, 0x3A, 0x6F, 0x86, 0xCC, 0x34, 0xE1};

uint32_t TimeInfo::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_DOUBLE)
			{
				xfer += iprot->readDouble(this->roundDuration);
				this->__isset.roundDuration = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_DOUBLE)
			{
				xfer += iprot->readDouble(this->univTime);
				this->__isset.univTime = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t TimeInfo::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("TimeInfo");

	xfer += oprot->writeFieldBegin("roundDuration", ::apache::thrift::protocol::T_DOUBLE, 10);
	xfer += oprot->writeDouble(this->roundDuration);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("univTime", ::apache::thrift::protocol::T_DOUBLE, 20);
	xfer += oprot->writeDouble(this->univTime);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(TimeInfo& a, TimeInfo& b)
{
	using ::std::swap;
	swap(a.roundDuration, b.roundDuration);
	swap(a.univTime, b.univTime);
	swap(a.__isset, b.__isset);
}

const char* FleetList::ascii_fingerprint = "A1C1A0D49440713B2A068AA50D07EE7A";
const uint8_t FleetList::binary_fingerprint[16] = {0xA1, 0xC1, 0xA0, 0xD4, 0x94, 0x40, 0x71, 0x3B, 0x2A, 0x06, 0x8A, 0xA5, 0x0D, 0x07, 0xEE, 0x7A};

uint32_t FleetList::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->fleetList.clear();
					uint32_t _size118;
					::apache::thrift::protocol::TType _etype121;
					xfer += iprot->readListBegin(_etype121, _size118);
					this->fleetList.resize(_size118);
					uint32_t _i122;
					for(_i122 = 0; _i122 < _size118; ++_i122)
					{
						xfer += this->fleetList[_i122].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.fleetList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->planetList.clear();
					uint32_t _size123;
					::apache::thrift::protocol::TType _etype126;
					xfer += iprot->readListBegin(_etype126, _size123);
					this->planetList.resize(_size123);
					uint32_t _i127;
					for(_i127 = 0; _i127 < _size123; ++_i127)
					{
						xfer += this->planetList[_i127].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.planetList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 30:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->fleetCount);
				this->__isset.fleetCount = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t FleetList::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("FleetList");

	xfer += oprot->writeFieldBegin("fleetList", ::apache::thrift::protocol::T_LIST, 10);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->fleetList.size()));
		std::vector<Fleet> ::const_iterator _iter128;
		for(_iter128 = this->fleetList.begin(); _iter128 != this->fleetList.end(); ++_iter128)
		{
			xfer += (*_iter128).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("planetList", ::apache::thrift::protocol::T_LIST, 20);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->planetList.size()));
		std::vector<Planet> ::const_iterator _iter129;
		for(_iter129 = this->planetList.begin(); _iter129 != this->planetList.end(); ++_iter129)
		{
			xfer += (*_iter129).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("fleetCount", ::apache::thrift::protocol::T_I32, 30);
	xfer += oprot->writeI32(this->fleetCount);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(FleetList& a, FleetList& b)
{
	using ::std::swap;
	swap(a.fleetList, b.fleetList);
	swap(a.planetList, b.planetList);
	swap(a.fleetCount, b.fleetCount);
	swap(a.__isset, b.__isset);
}

const char* PlanetList::ascii_fingerprint = "18C7E957C40A9FD4002304AEBEA00438";
const uint8_t PlanetList::binary_fingerprint[16] = {0x18, 0xC7, 0xE9, 0x57, 0xC4, 0x0A, 0x9F, 0xD4, 0x00, 0x23, 0x04, 0xAE, 0xBE, 0xA0, 0x04, 0x38};

uint32_t PlanetList::read(::apache::thrift::protocol::TProtocol* iprot)
{

	uint32_t xfer = 0;
	std::string fname;
	::apache::thrift::protocol::TType ftype;
	int16_t fid;

	xfer += iprot->readStructBegin(fname);

	using ::apache::thrift::protocol::TProtocolException;


	while(true)
	{
		xfer += iprot->readFieldBegin(fname, ftype, fid);
		if(ftype == ::apache::thrift::protocol::T_STOP)
		{
			break;
		}
		switch(fid)
		{
		case 10:
			if(ftype == ::apache::thrift::protocol::T_LIST)
			{
				{
					this->planetList.clear();
					uint32_t _size130;
					::apache::thrift::protocol::TType _etype133;
					xfer += iprot->readListBegin(_etype133, _size130);
					this->planetList.resize(_size130);
					uint32_t _i134;
					for(_i134 = 0; _i134 < _size130; ++_i134)
					{
						xfer += this->planetList[_i134].read(iprot);
					}
					xfer += iprot->readListEnd();
				}
				this->__isset.planetList = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		case 20:
			if(ftype == ::apache::thrift::protocol::T_I32)
			{
				xfer += iprot->readI32(this->planetCount);
				this->__isset.planetCount = true;
			}
			else
			{
				xfer += iprot->skip(ftype);
			}
			break;
		default:
			xfer += iprot->skip(ftype);
			break;
		}
		xfer += iprot->readFieldEnd();
	}

	xfer += iprot->readStructEnd();

	return xfer;
}

uint32_t PlanetList::write(::apache::thrift::protocol::TProtocol* oprot) const
{
	uint32_t xfer = 0;
	xfer += oprot->writeStructBegin("PlanetList");

	xfer += oprot->writeFieldBegin("planetList", ::apache::thrift::protocol::T_LIST, 10);
	{
		xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->planetList.size()));
		std::vector<Planet> ::const_iterator _iter135;
		for(_iter135 = this->planetList.begin(); _iter135 != this->planetList.end(); ++_iter135)
		{
			xfer += (*_iter135).write(oprot);
		}
		xfer += oprot->writeListEnd();
	}
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldBegin("planetCount", ::apache::thrift::protocol::T_I32, 20);
	xfer += oprot->writeI32(this->planetCount);
	xfer += oprot->writeFieldEnd();

	xfer += oprot->writeFieldStop();
	xfer += oprot->writeStructEnd();
	return xfer;
}

void swap(PlanetList& a, PlanetList& b)
{
	using ::std::swap;
	swap(a.planetList, b.planetList);
	swap(a.planetCount, b.planetCount);
	swap(a.__isset, b.__isset);
}

} // namespace
